### ISSUE TITLE
[9.0.1] n

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#1092]
### Expected behavior

That after an /usr/bin/killall -HUP gvmd  the log file is written again.

### Actual behavior

After moving the log files and send HUP no more log files are generated.

### Steps to reproduce

1. Call logrotate

### GVM versions
**gvm:**  9.0.1

**gvm-libs:** 11.0.1

### Environment

**Operating system:** CentOS 7.8

**Comment by y0urself** [comment]
We do not support gvmd v9.0.1 anymore.
