### ISSUE TITLE
 manage_update_nvt_cache_osp: failed to get scanner_version

### ISSUE THREAD

**Issue by rglavina** [greenbone/gvmd#1132]
### Expected behavior

NVTs 59952 of 59952 in GSA

### Actual behavior

No NVT available in GSA

### Steps to reproduce

1. Login to GSA
2. SecInfo
3.NVTs

### GVM versions

Greenbone Security Assistant 9.0.1 (gsad --version)
Greenbone Vulnerability Manager 9.0.1 (gvmd --version)
OpenVAS 7.0.1 (openvas --version)
gvm-libs 11.0.1
ospd-openvas 1.0.1 

### Environment

**Operating system:**
Linux openvas11 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

**Installation method / source:** ( source installation)

### Logfiles
openvas.log
lib  nvticache:MESSAGE:2020-06-11 12h11.43 utc:18636: Updated NVT cache from version 0 to 202006101059

gvmd.log
md manage:   INFO:2020-06-11 14h00.49 utc:33013:    Rebuilding NVTs.
md manage:WARNING:2020-06-11 14h00.49 utc:33013: database must be initialised from scanner
lib  osp:WARNING:2020-06-11 14h01.00 utc:33013: osp_get_vts_version: element VTS missing.
lib  osp:WARNING:2020-06-11 14h01.01 utc:33028: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-11 14h01.01 utc:33028: manage_update_nvt_cache_osp: failed to get scanner_version

lib  osp:WARNING:2020-06-11 14h49.59 utc:38205: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-11 14h49.59 utc:38205: manage_update_nvt_cache_osp: failed to get scanner_version

**Comment by bjoernricks** [comment]
Could you please check the log file of ospd-openvas? Maybe also change the log output to include debug messages. It is very likely that ospd-openvas is still updating the feed. In that case it doesn't return a scanner version to gvmd.

**Comment by rglavina** [comment]
Following outputs from ospd-openvas (DEBUG) e gmvd.  
tail -5 ospd-scanner.log
2020-06-17 13:25:37,741 OSPD - openvas: DEBUG: (ospd.server) New connection from /opt/gvm/var/run/ospd.sock
2020-06-17 13:25:57,881 OSPD - openvas: DEBUG: (ospd.server) New connection from /opt/gvm/var/run/ospd.sock
2020-06-17 13:26:07,934 OSPD - openvas: DEBUG: (ospd.server) New connection from /opt/gvm/var/run/ospd.sock
2020-06-17 13:26:28,009 OSPD - openvas: DEBUG: (ospd.server) New connection from /opt/gvm/var/run/ospd.sock
2020-06-17 13:26:38,058 OSPD - openvas: DEBUG: (ospd.server) New connection from /opt/gvm/var/run/ospd.sock

 tail -10 gvmd.log
lib  osp:WARNING:2020-06-17 11h25.27 utc:45694: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-17 11h25.27 utc:45694: manage_update_nvt_cache_osp: failed to get scanner_version
lib  osp:WARNING:2020-06-17 11h25.47 utc:47084: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-17 11h25.47 utc:47084: manage_update_nvt_cache_osp: failed to get scanner_version
lib  osp:WARNING:2020-06-17 11h26.07 utc:47175: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-17 11h26.07 utc:47175: manage_update_nvt_cache_osp: failed to get scanner_version
lib  osp:WARNING:2020-06-17 11h26.17 utc:47193: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-17 11h26.17 utc:47193: manage_update_nvt_cache_osp: failed to get scanner_version
lib  osp:WARNING:2020-06-17 11h26.38 utc:47226: osp_get_vts_version: element VTS missing.
md manage:WARNING:2020-06-17 11h26.38 utc:47226: manage_update_nvt_cache_osp: failed to get scanner_version

**Comment by cfi-gb** [comment]
@bjoernricks @rglavina I have removed the "bug" label for now because i don't think that this is a bug but rather just a lack of documentation. Basically i have only seen these messages if the default OSPD socket path wasn't updated (yet). As there wasn't any documentation about that published i have updated the INSTALL.md to include this info now: #1202

**Comment by cfi-gb** [comment]
#1202 was merged, closing for now.

@rglavina Feel free to do a short ping here if following the instructions doesn't make your feed update to work again.
