### ISSUE TITLE
Master slave, slave report <uuid> missing UUID

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gvmd#1148]
### Expected behavior
Run task from GSA on master to slave. Job runs successfully and slave returns report to master.

### Actual behavior
Scheduled task starts, the logs on master show its starting it to the slave. The slave receives the task and starts to run it. On master the task status stays at Requested. The slave finishes the task, then the master starts to log errors. Master task status remains requested.

### Logfiles
```
md manage:WARNING:2020-06-24 07h02.54 UTC:18361: slave_setup: slave report a39e84c6-936a-4044-a771-78646b7beeb3 missing UUID
md manage:WARNING:2020-06-24 07h03.19 UTC:18381: slave_setup: slave report 93b3d258-3c09-4ab6-a6a2-410c08ea6508 missing UUID
md manage:WARNING:2020-06-24 07h03.19 UTC:18361: slave_setup: slave report a39e84c6-936a-4044-a771-78646b7beeb3 missing UUID
md manage:WARNING:2020-06-24 07h03.44 UTC:18381: slave_setup: slave report 93b3d258-3c09-4ab6-a6a2-410c08ea6508 missing UUID
md manage:WARNING:2020-06-24 07h03.44 UTC:18361: slave_setup: slave report a39e84c6-936a-4044-a771-78646b7beeb3 missing UUID
md manage:WARNING:2020-06-24 07h04.09 UTC:18381: slave_setup: slave report 93b3d258-3c09-4ab6-a6a2-410c08ea6508 missing UUID
md manage:WARNING:2020-06-24 07h04.09 UTC:18361: slave_setup: slave report a39e84c6-936a-4044-a771-78646b7beeb3 missing UUID
```

### Steps to reproduce
Run a task on a slave.

GVM versions
gsa: 9.0.1~git-ca16c9fb6-gsa-9.0
gvm: 9.0.1~git-f17f9a71-gvmd-9.0
OpenVAS: 7.0.1
gvm-libs: 11.0.1

### Environment
Operating system:
Linux xxxxxxxxx 4.15.0-101-generic 102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

**Comment by BasvanH** [comment]
Master gvmd log shows task is still running:
```
18361 ?        S      0:40 gvmd: GMP: Handling slave scan 141740de-5c00-4305-8a86-2b75722029ab
18381 ?        S      0:40 gvmd: GMP: Handling slave scan 995e5ca1-d172-4860-883c-45587a360ad8
```
While on the slaves the tasks are done.

**Comment by BasvanH** [comment]
Correction, the task is not gone on the slave. They are still there ready to be read by the master.

**Comment by BasvanH** [comment]
If any additional logs are required. I'll be more then happy to provide them. Currently my master/slave doesn't work because of this issue.

**Comment by BasvanH** [comment]
Any news on this perhaps?

**Comment by BasvanH** [comment]
@timopollmeier, could you kindly take a look at this issue please.

**Comment by mattmundell** [comment]
> @timopollmeier, could you kindly take a look at this issue please.

It's on my list, just have to finish another one first.

**Comment by mattmundell** [comment]
I've run a few GMP slave tasks on 20.08 and OpenVAS-11 but I don't see the error.  I also tried running from a schedule.

From the error message it looks like the task exists on the slave but has no reports.  Can you confirm?  Not sure what would cause this.  Perhaps "Auto Delete Reports" is being set on the slave task somehow?

Note that 20.08 should be out by the end of August, which may solve your issue.

**Comment by BasvanH** [comment]
Sorry for the delay, I was on a holiday.

I will collect a full run of this with all the logs and findings, so this may help you troubleshoot it.

**Comment by BasvanH** [comment]
Alright, have restarted master and the two slaves, and started two jobs.

|Task|UUID|Slave|
|---|---|---|
|External subnets - NVT|702339fe-3811-4f7a-9f4f-9bd281cf8553|01
|Internal subnets - NVT|a7edeb45-dbb0-45a5-930d-b1bd3158f707|02

**Master logs**
```
md   main:MESSAGE:2020-08-10 11h23.17 utc:15628:    Greenbone Vulnerability Manager version 9.0.1~git-f17f9a71-gvmd-9.0 (GIT revision f17f9a71-gvmd-9.0) (DB revision 221)
md manage:WARNING:2020-08-10 11h23.17 utc:15629: database must be initialised from scanner
util gpgme:MESSAGE:2020-08-10 11h23.17 utc:15629: Setting GnuPG dir to '/opt/gvm/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-08-10 11h23.17 utc:15629: Using OpenPGP engine version '2.2.4'
event task:MESSAGE:2020-08-10 11h24.16 UTC:15824: Task External subnets - NVT (702339fe-3811-4f7a-9f4f-9bd281cf8553) has been modified by xxxx
event task:MESSAGE:2020-08-10 11h24.21 UTC:15864: Status of task External subnets - NVT (702339fe-3811-4f7a-9f4f-9bd281cf8553) has changed to Requested
event task:MESSAGE:2020-08-10 11h24.21 UTC:15864: Task External subnets - NVT (702339fe-3811-4f7a-9f4f-9bd281cf8553) has been requested to start by xxxx
event task:MESSAGE:2020-08-10 11h25.39 UTC:15870: Status of task External subnets - NVT (702339fe-3811-4f7a-9f4f-9bd281cf8553) has changed to Running
event task:MESSAGE:2020-08-10 12h50.34 UTC:24791: Task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) has been modified by xxxx
event task:MESSAGE:2020-08-10 12h50.39 UTC:24847: Status of task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) has changed to Requested
event task:MESSAGE:2020-08-10 12h50.39 UTC:24847: Task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) has been requested to start by xxxx
```
**Slave 01 logs**
```
md   main:MESSAGE:2020-08-10 11h20.34 utc:25081:    Greenbone Vulnerability Manager version 9.0.1~git-f17f9a71-gvmd-9.0 (GIT revision f17f9a71-gvmd-9.0) (DB revision 221)
md manage:WARNING:2020-08-10 11h20.34 utc:25082: database must be initialised from scanner
util gpgme:MESSAGE:2020-08-10 11h20.35 utc:25082: Setting GnuPG dir to '/opt/gvm/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-08-10 11h20.35 utc:25082: Using OpenPGP engine version '2.2.4'
event target:MESSAGE:2020-08-10 11h24.21 UTC:25252: Target c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (a60aabe4-79f4-4697-b255-244f75033356) has been created by admin
md manage:WARNING:2020-08-10 11h24.23 UTC:25252: insert_nvt_selectors: skipping NVT '1.3.6.1.4.1.25623.1.0.80109' from import of config '3fcb2cae-6067-41f0-a7c0-e8be85d71e4b' because the NVT is missing from the cache
event config:MESSAGE:2020-08-10 11h24.24 UTC:25252: Scan config c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (580c1394-d695-4a26-8599-dbc74feaeaba) has been created by admin
event task:MESSAGE:2020-08-10 11h24.24 UTC:25252: Status of task  (ab6b2747-92e4-4695-8499-956b1bd1200d) has changed to New
event task:MESSAGE:2020-08-10 11h24.24 UTC:25252: Task c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (ab6b2747-92e4-4695-8499-956b1bd1200d) has been created by admin
event task:MESSAGE:2020-08-10 11h24.24 UTC:25252: Status of task c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (ab6b2747-92e4-4695-8499-956b1bd1200d) has changed to Requested
event task:MESSAGE:2020-08-10 11h24.24 UTC:25252: Task c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (ab6b2747-92e4-4695-8499-956b1bd1200d) has been requested to start by admin
event task:MESSAGE:2020-08-10 11h25.16 UTC:25255: Status of task c40d3876-50cc-481d-b22e-a62427ac8d73 for External subnets - NVT (ab6b2747-92e4-4695-8499-956b1bd1200d) has changed to Running
```
**Slave 02 logs**
```
md   main:MESSAGE:2020-08-10 11h35.34 utc:23276:    Greenbone Vulnerability Manager version 9.0.1~git-f17f9a71-gvmd-9.0 (GIT revision f17f9a71-gvmd-9.0) (DB revision 221)
md manage:WARNING:2020-08-10 11h35.34 utc:23284: database must be initialised from scanner
util gpgme:MESSAGE:2020-08-10 11h35.35 utc:23284: Setting GnuPG dir to '/opt/gvm/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-08-10 11h35.35 utc:23284: Using OpenPGP engine version '2.2.4'
event target:MESSAGE:2020-08-10 12h50.39 UTC:26438: Target b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (43a3ad59-7c9c-4321-b65f-17e48f6614ba) has been created by admin
md manage:WARNING:2020-08-10 12h50.41 UTC:26438: insert_nvt_selectors: skipping NVT '1.3.6.1.4.1.25623.1.0.80109' from import of config '579e4bac-d41d-4087-a331-1c8407be0d92' because the NVT is missing from the cache
event config:MESSAGE:2020-08-10 12h50.42 UTC:26438: Scan config b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (f41130e1-2462-455f-8ad5-06309478ec1a) has been created by admin
event task:MESSAGE:2020-08-10 12h50.42 UTC:26438: Status of task  (54d63e6a-7cc9-4813-b46f-42a7c7437152) has changed to New
event task:MESSAGE:2020-08-10 12h50.42 UTC:26438: Task b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (54d63e6a-7cc9-4813-b46f-42a7c7437152) has been created by admin
event task:MESSAGE:2020-08-10 12h50.42 UTC:26438: Status of task b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (54d63e6a-7cc9-4813-b46f-42a7c7437152) has changed to Requested
event task:MESSAGE:2020-08-10 12h50.42 UTC:26438: Task b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (54d63e6a-7cc9-4813-b46f-42a7c7437152) has been requested to start by admin
event task:MESSAGE:2020-08-10 12h51.52 UTC:26441: Status of task b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT (54d63e6a-7cc9-4813-b46f-42a7c7437152) has changed to Running
```

Task `702339fe-3811-4f7a-9f4f-9bd281cf8553` on slave **01** goes to **Running**, and master detects it.
Task `a7edeb45-dbb0-45a5-930d-b1bd3158f707` on slave **02** goes to **Running**, and master does not detect it.

Please guide me a bit to the tables in order to provide you with the troubleshooting information.

**Comment by mattmundell** [comment]
Is this some sort of network issue?  Perhaps slave 02 can see the request from master, but master cannot see the response from slave 02?  This would explain why the task start on slave but master does not get updated.

**Comment by mattmundell** [comment]
Also note that we will hopefully drop GMP slaves in the future (maybe 21.04).  So it may be better to use an OSP scanner.

**Comment by BasvanH** [comment]
> Also note that we will hopefully drop GMP slaves in the future (maybe 21.04). So it may be better to use an OSP scanner.

As far as my knowledge goes, you can only have multiple NVT's in a master/slave setup.

**Comment by BasvanH** [comment]
> Is this some sort of network issue? Perhaps slave **02** can see the request from master, but master cannot see the response from slave **02**? This would explain why the task starts on slave but master does not get updated.

No, network issues. Same VLAN, have full operating DNS & reversed DNS, can ping to all, no firewall ons the boxes.

Today the `702339fe-3811-4f7a-9f4f-9bd281cf8553` is going well, but could be it will have the same issue tomorrow.

I have some DB results, slave 02 is generating a report for `a7edeb45-dbb0-45a5-930d-b1bd3158f707` with GUID `6ef96e97-f255-4243-b339-4cb6696a9a54`.
**Master tasks**
|id|uuid|owner|name|hidden|comment|run_status|start_time|end_time|config|target|schedule|schedule_next_time|schedule_periods|scanner|config_location|target_location|schedule_location|scanner_location|upload_result_count|hosts_ordering|alterable|creation_time|modification_time|usage_type
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|15|a7edeb45-dbb0-45a5-930d-b1bd3158f707|2|Internal subnets - NVT|0|Schedule B|3|0|0|1|4|0||0|27|0|0|0|0||sequential|1|1585303816|1597063835|scan|

**Master reports**
|id|uuid|owner|task|date|start_time|end_time|comment|scan_run_status|slave_progress|slave_task_uuid|slave_uuid|slave_name|slave_host|slave_port|source_iface|flags||1|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|355|6ef96e97-f255-4243-b339-4cb6696a9a54|2|15|1597063839||||3|0|54d63e6a-7cc9-4813-b46f-42a7c7437152|ca8e7f06-cfbd-4267-9ea9-0b3c699c3665|GVM SLAVE02|slave02.domain.local|9391||0|

**Slave 02 tasks**
|id|uuid|owner|name|hidden|comment|run_status|start_time|end_time|config|target|schedule|schedule_next_time|schedule_periods|scanner|config_location|target_location|schedule_location|scanner_location|upload_result_count|hosts_ordering|alterable|creation_time|modification_time|usage_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|42|54d63e6a-7cc9-4813-b46f-42a7c7437152|1|b8d7f19d-d894-4720-82b5-31f0f6ecf581 for Internal subnets - NVT|0|Slave task for master task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) report 6ef96e97-f255-4243-b339-4cb6696a9a54.|4|||76|42|0|0||1|0|0|0|0||sequential|0|1597063842|1597063842|scan|
|36|c7c1fbb9-69ae-4e0a-a29a-4765b87e3995|1|8a5937d1-0fd6-4a86-88ce-5d42e0242302 for Internal subnets - NVT|2|Slave task for master task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) report 25d2108d-c062-47e0-87eb-1204e7db5fa7.|1||1591920670|70|36|0|0||1|0|0|0|0||sequential|0|1591913109|1591913109|scan|
|41|93b3d258-3c09-4ab6-a6a2-410c08ea6508|1|63d40f05-687f-452c-b20f-4e106a87e88d for Internal subnets - NVT|2|Slave task for master task Internal subnets - NVT (a7edeb45-dbb0-45a5-930d-b1bd3158f707) report 995e5ca1-d172-4860-883c-45587a360ad8.|1||1592702352|75|41|0|0||1|0|0|0|0||sequential|0|1592690718|1592690718|scan|

**Slave 02 reports**
|id|uuid|owner|task|date|start_time|end_time|comment|scan_run_status|slave_progress|
|---|---|---|---|---|---|---|---|---|---|
|48|a7f5bbc7-817a-4ab8-adce-1f25ca026e50|1|48|1591186347|1591186364|1591186405|1|100|0|

The slave tells the master which report GUID it's using, so I see no reason for communications problem.

**Comment by mattmundell** [comment]
Maybe just a typo but the Slave 02 report has a task 48 but the slave 02 task is 42.

> The slave tells the master which report GUID it's using, so I see no reason for communications problem.

Yes makes sense.

**Comment by BasvanH** [comment]
> Maybe just a typo but the Slave 02 report has a task 48 while the slave 02 task is 42.

Sorry about that, yes, double checked and was typo issue.

**Comment by mattmundell** [comment]
Hmm, so the report's on the slave but not the master.

Is there a gvmd process on the master handling the slave?  Maybe it died -- although you should see that in the logs.

You could turn on full logging and see what the gvmd process is getting from the slave.

**Comment by BasvanH** [comment]
> Is there a gvmd process on the master handling the slave? Maybe it died -- although you should see that in the logs.
Yes there is:
```
ps -ax | grep gvmd
  658 ?        S      0:00 gvmd: Reloading NVTs
  660 ?        S      0:00 gvmd: OSP: Updating NVT cache
  662 ?        Ss     0:00 postgres: 10/main: gvm gvmd [local] idle
  686 pts/1    S+     0:00 grep --color=auto gvmd
10676 ?        Ss     0:10 postgres: 10/main: grafana gvmd 127.0.0.1(57042) idle
11821 ?        Ss     0:00 gpg-agent --homedir /opt/gvm/var/lib/gvm/gvmd/gnupg --use-standard-socket --daemon
15629 ?        SL     0:12 gvmd: Waiting for incoming connections
15653 ?        Ss     0:04 postgres: 10/main: gvm gvmd [local] idle
15870 ?        S      0:29 gvmd: GMP: Handling slave scan 901340bc-3e13-4b21-b4aa-46e123461baa
15871 ?        Ss     1:22 postgres: 10/main: gvm gvmd [local] idle
16223 ?        Ss     0:00 postgres: 10/main: grafana gvmd 127.0.0.1(57316) idle
17506 ?        Ss     0:00 postgres: 10/main: grafana gvmd 127.0.0.1(57318) idle
24853 ?        S      0:00 gvmd: GMP: Handling slave scan 6ef96e97-f255-4243-b339-4cb6696a9a54 <- here it is
24854 ?        Ss     0:00 postgres: 10/main: gvm gvmd [local] idle
32489 ?        Ss     0:00 postgres: 10/main: grafana gvmd 127.0.0.1(57342) idle
```

**Comment by BasvanH** [comment]
> You could turn on full logging and see what the gvmd process is getting from the slave.

Could you tell me how to do this?

**Comment by mattmundell** [comment]
https://github.com/greenbone/gvmd/blob/master/INSTALL.md#logging-configuration

Basically replace 127 with 128 in etc/gvm/gvmd_log.conf.  Watch out, it gets overwritten on ````make install````.

**Comment by BasvanH** [comment]
Sorry it took a while @mattmundell, I now have managed to capture the issue with the debug logs. These logs contain possible sensitive data, so how can I share those logs with you privately?

**Comment by mattmundell** [comment]
Don't really have capacity to check the logs now, but please try with 20.08

    https://community.greenbone.net/t/gvm-20-08-stable-initial-release-2020-08-12/6312

**Comment by BasvanH** [comment]
Ok understood, will do and report back.

**Comment by BasvanH** [comment]
Unfortunately 20.08 has the exact same problems.

'''
md manage:WARNING:2020-09-04 08h32.09 UTC:19325: slave_setup: slave report 55e12987-0ad3-47a4-a43e-fa9a01d35254 missing UUID
md manage:WARNING:2020-09-04 08h32.17 UTC:19326: slave_setup: slave report 726ec89b-1ecb-4198-b0fe-a0419e4bed69 missing UUID
'''

**Comment by bjoernricks** [comment]
GMP Sensors have been dropped with 21.04.
