### ISSUE TITLE
gvmd-pg config file generation does not HTML escape password characters for postgres url

### ISSUE THREAD

**Issue by ScottMnemonic** [greenbone/gvmd#1156]
### Expected behavior
Passwords utilized via URL should be html encoded.
IE
`export GVMD_POSTGRESQL_URI=postgresql://gvmduser:p%40ssw0rd@localhost:5432/gvmd?application_name=gvmd
`

### Actual behavior
Passwords are entered into /etc/default/gvmd-pg as plain text.
`export GVMD_POSTGRESQL_URI=postgresql://gvmduser:p@ssw0rd@localhost:5432/gvmd?application_name=gvmd
`
### Steps to reproduce

1. Install GVM on Ubuntu 18.04 via the ppa (`ppa:mrazavi/gvm`) (`sudo apt install gvm`)
2. Provide a password when prompted with special characters such as `@`
3. Open `/etc/default/gvmd-pg` to see special character without html encoding.

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 9.0
**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 9.0.0
Manager DB revision 221
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
**openvas-scanner:** (openvas --version)
OpenVAS 7.0.0
Most new code since 2005: (C) 2019 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm-libs:**

### Environment

**Operating system:**

Linux <IP> 5.3.0-1023-aws #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

**Installation method / source:** (packages, source installation)
ppa:mrazavi/gvm
apt install gvm

**Comment by bjoernricks** [comment]
Hi this is not an issue with gvmd itself. It is a packaging issue. Please report this issue at the ppa:mrazavi/gvm.

GVMD_POSTGRESQL_URI is not used in gvmd and also not /etc/default/gvmd-pg
