### ISSUE TITLE
 openvas_scanner_connect_unix: Failed to connect to scanner

### ISSUE THREAD

**Issue by manju1920** [greenbone/gvmd#1174]
Hi,
Recently I could not able to compile gvm-libs-10.0.2 on CentOS 7.8. Hence I have installed greenbone freshly on Debian GNU/Linux 10 (buster) to migrate tasks. I took backup of gvmd.db file from CentOS server and moved to Debian Server. After that I'm getting "openvas_scanner_connect_unix: Failed to connect to scanner (/var/run/openvassd.sock): No such file or directory" message and I could not start new scan.

Please help me on this.

**Comment by cfi-gb** [comment]
Please note that the Greenbone issue trackers are only used for bug reports as stated in the [issue templates](https://raw.githubusercontent.com/greenbone/gvmd/master/.github/ISSUE_TEMPLATE/bug-report.md) which should show up in each repository when creating a new issue:

> 1. Be aware that this is not a support forum. If your issue is rather a question than a bug report, please use our community forum at https://community.greenbone.net/c/gse instead.

Based on this i'm closing the issue as "invalid".

Limited user support is given at https://community.greenbone.net/c/gse

Thanks for your help in the future to keep the communication channels clean.
