### ISSUE TITLE
Scheduled tasks cannot be resumed

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1187]
**Expected behaviour:**
Scheduled tasks should be able to resume after being stopped, like any tasks

**Actual behaviour:**
Scheduled tasks cannot be resumed. Resume button is greyed out.

**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**HowTo Reproduce:**
Set a schedule to a task. Start it manually. After a few percentages achieved, stop it. Task cannot be resumed.

**How To Fix:**
Remove the schedule from the task. Resume button is now no longer greyed out and task can be resumed.

**Comment by y0urself** [comment]
We do not support gvmd v9 anymore.
