### ISSUE TITLE
gvmd doesn't correctly handle pending updates on ospd-openvas scanners

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1190]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**Current behaviour:**
When gvmd request a new scan task to run, if the scanner has a pending update waiting or is being updated, then task will be automatically put in Done status which is wrong.

**Expected behaviour:** 
When such scenario happens, gvmd should put the task in queue and resume it as soon as the update is finished, so that task can be run normally. This is especially important for scheduled tasks, or tasks started via the Start Task alert mechanism, where tasks are automatically started without the control of an operator.

**How to Reproduce:**
On a scanner in use (eg; running a task), launch a feed update. Since scanner is running, update will be set in pending mode. Then launch a second scan task on the same scanner. This second task will be automatically set in Done status since a feed update is pending.

**Comment by y0urself** [comment]
We do not support gvmd v9.0.1 anymore.
