### ISSUE TITLE
gvmd randomely drop running scan tasks

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1197]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**gvmd run options:**
`/opt/gvm/sbin/gvmd  --osp-vt-update=/opt/gvm/var/run/ospd.sock --max-ips-per-target=10000 --inheritor=admin --unix-socket=/opt/gvm/var/run/gvmd.sock --slave-commit-size=10000 `

**Current behaviour:** 
Occasionaly, gvmd will drop running scan tasks by automatically putting them in Stopped state. This happens randomely, on somehow large tasks (>1024 IP) without any user interaction. Right before the task get dropped, there is an OSP error saying that the scan cannot be found:

```
md manage:WARNING:2020-07-14 20h45.00 CEST:14966: OSP get_osp_scan_status 68cab482-415c-4475-9f9b-d2dcd6f562b3: Failed to find scan '68cab482-415c-4475-9f9b-d2dcd6f562b3'
md manage:WARNING:2020-07-14 20h45.15 CEST:14966: OSP get_scan 68cab482-415c-4475-9f9b-d2dcd6f562b3: Failed to find scan '68cab482-415c-4475-9f9b-d2dcd6f562b3'
event task:MESSAGE:2020-07-14 20h46.06 CEST:14966: Status of task Electropole, Infrastructure Networks (6d6f7472-c2e0-4fdf-9f02-2ffca8453836) has changed to Stopped
```
However, as you would have noticed, the scan UUIDs do not match. The first UUID is the one assigned by the ospd-openvas scanner. 

On ospd-openvas side; scan is still running and no errors is logged.

**Expected behaviour:**
Gvmd should not automatically stop running tasks and logging should be improved to synchronize UUIDs to ease readability.

**How to reproduce:**
It seems to happens more frequently when gvmd is loaded; eg while multiple tasks are running simultaneously. However, the machine hosting the installation has no capacity outage. It has plenty of RAM and CPUs available. I have not found any way to reproduce this issue, unfortunately. But this generally happens once a week, at different times, on our central scanning plateform which is in production (that is, continuously having running tasks scans)

**Comment by jstevensog** [comment]
Have a similar issue, not quite the same log entries.  A task will randomly stop, and when restarted at a later time will instantly go to Done.
gvmd.log shows:
md manage:WARNING:2020-09-09 00h07.08 AEST:240545: Could not connect to Scanner at /opt/gvm/var/run/ospd.sock
md manage:WARNING:2020-09-09 00h07.09 AEST:240545: Could not connect to Scanner at /opt/gvm/var/run/ospd.sock
event task:MESSAGE:2020-09-09 00h07.09 AEST:240545: Status of task APB (89b2efdb-3871-42a3-b456-b8f0772bd004) has changed to Stopped

OS:  CentOS Linux release 8.2.2004
gvmd version: Greenbone Vulnerability Manager 21.4.0~dev1~git-5fa87957-master
OpenVAS version: OpenVAS 7.0.1
gvm-libs 11.0.1

Appears to be that for some reason the ospd.sock becomes unavailable.

**Comment by cfi-gb** [comment]
Probably already solved with https://github.com/greenbone/ospd-openvas/pull/390

**Comment by wisukind** [comment]
Thanks for notifying us cfi. Will certainly help improve the overrall reliability of the gvmd <-> ospd-openvas communication.
