### ISSUE TITLE
Feature Request: Zip/Bzip2 reports sent by email

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1198]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```
**Current behaviour:**
Currently when an alert is set to automatically send reports via email; reports are sent non compressed. Which may quickly reach the size limit of the SMTP server  / mail service environment while xls & pdf files containing only texts may compress easily. 

**Request proposed:**
Allow an option to automatically compress attached reports before sending them via mail. It should at least allow zip and bzip2 compression algorithms.

**Comment by y0urself** [comment]
We do not support gvmd v9.0.1 anymore.
