### ISSUE TITLE
can‘t login or create user or --get-users

### ISSUE THREAD

**Issue by BerialJ** [greenbone/gvmd#1218]
sudo gvmd --create-user=admin 
sudo gvmd --get-users         
sudo gvmd --create-user admin
sudo gvmd --get-users    

using kali linux
openvas-start got missing today，gvm-check~ shows installed OK，but can’t login ，
then find out maybe it can‘t create a user at all.

**Comment by cfi-gb** [comment]
Please see:

https://community.greenbone.net/t/not-able-to-create-admin-account-gvm-start-not-running-due-to-several-errors-in-kali-linux/6141/5

I'm closing this issue as invalid for now.
