### ISSUE TITLE
[20.08] gvmd: database is wrong version

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gvmd#1270]
Upgraded to v20.08, and when starting gvmd I get an error in the gvmd log:

```
md   main:MESSAGE:2020-08-25 10h07.24 utc:4489:    Greenbone Vulnerability Manager version 20.08.0~git-bc5f9ac0-gvmd-20.08 (GIT revision bc5f9ac0-gvmd-20.08) (DB revision 233)
md manage:MESSAGE:2020-08-25 10h07.24 utc:4502: check_db_versions: database version of database: 221
md manage:MESSAGE:2020-08-25 10h07.24 utc:4502: check_db_versions: database version supported by manager: 233
md   main:CRITICAL:2020-08-25 10h07.24 utc:4502: gvmd: database is wrong version
```

### GVM versions
**gsa:**
Greenbone Security Assistant 20.08.0~git-8fad03cb0-gsa-20.08

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 20.08.0~git-bc5f9ac0-gvmd-20.08

**openvas-scanner:** (openvas --version)
OpenVAS 20.8.0

**gvm-libs:**
gvm-libs 20.8.0~git-9ae098bc-gvm-libs-20.08

**Comment by cfi-gb** [comment]
This is not a bug, you just need to upgrade the database:

https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#migrating-the-database

**Comment by BasvanH** [comment]
I feel stupid, RTFM, got it working. Thanks @cfi-gb

**Comment by cfi-gb** [comment]
@BasvanH No worries, the documentation and message around this currently isn't that clear. I have updated the INSTALL.md in #1272 and raised #1271 for an improved message in the logs.
