### ISSUE TITLE
Extend "database is wrong version" with info about "gvmd --migrate"

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/gvmd#1271]
There are the following to messages:

https://github.com/greenbone/gvmd/blob/v20.8.0/src/gvmd.c#L2648

https://github.com/greenbone/gvmd/blob/v20.8.0/src/manage_sql.c (Line 934)

I don't know the details on both message and for which cases these are showing up but it could help for issues like #1270 to include some info on `gvmd --migrate` and other special cases (e.g. if a downgrade is tried) in that message.

**Comment by bjoernricks** [comment]
The message should be improved that it states gvmd --migrate should be run.
