### ISSUE TITLE
got nvts missing ,having trouble fixing or reinstall 

### ISSUE THREAD

**Issue by BerialJ** [greenbone/gvmd#1290]
scan and get nothing,findout it's nvts are missing.
don't know why ,another problem with Kali?

greenbones-nvt-sync didn't work,

tried copy nvts in openvas folder into gvm folder and did not work.

tried reinstall ,i mean apt purge gvm ,apt autoremove ,apt autoclean.
but users(admin) is still there,also the password.

installed in another Kali and it runs ok. 

so what's the right way to reinstall?

**Comment by cfi-gb** [comment]
From the issue template which should show up during issue creation:

> Before reporting an issue please:
>
> 1. Be aware that this is not a support forum. If your issue is rather a question
>    than a bug report, please use our community forum at
>    https://community.greenbone.net/c/gse instead.

thus closing as "invalid".

Please ask for support at the linked community portal, if doing so please be more specific (e.g. there is no such thing like "didn't work", please explain in detail what this means).
