### ISSUE TITLE
"Scan Configs" are not created, in a clean installation.

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/gvmd#1315]
### Actual behavior

![image](https://user-images.githubusercontent.com/17960988/95166570-8138e880-0784-11eb-9156-bace052f42c3.png)

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 20.08.0~git

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 20.08.0
Manager DB revision 233
Copyright (C) 2010-2020 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas-scanner:** (openvas --version)
OpenVAS 20.8.0

**gvm-libs:**
gvm-libs 20.8.0

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by cfi-gb** [comment]
@dgiorgio Please use https://community.greenbone.net/c/gse/16 for support questions / requests like this.

Nevertheless a short hint:

You're probably have missed to set the Feed Import user:

https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#set-the-feed-import-owner

or haven't synced the GVM_DATA feed yet:

https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#keeping-the-feeds-up-to-date

If you have further questions / issues with the above please create a new community portal posting.

**Comment by cfi-gb** [comment]
Sorry, forget to mention. If there is a bug in the creation of the scan config (which is currently very unlikely) then please provide more details in this issue (e.g. steps to reproduce) and we still can re-open this issue.
