### ISSUE TITLE
[gvmd 20.08] Scanning task reaching 99% may change to Interrupted state for no reason

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1322]
gvmd --version
Greenbone Vulnerability Manager 20.08.0~git-3276b8ff-gvmd-20.08
GIT revision 3276b8ff-gvmd-20.08
Manager DB revision 233

openvas  --version
OpenVAS 20.8.0
gvm-libs 20.8.0~git-3597093-gvm-libs-20.08_

**Operating System:** Ubuntu 18.04 LTS

**Current behaviour:** Occasionally, scanning tasks almost done (99% percentage reached) may change from Running to Interrupted state. No error is logged on ospd-openvas  / openvas side. On gvmd side, the only log is:

`event task:MESSAGE:2020-10-09 07h09.30 UTC:17932: Status of task XYZ (ac9bf171-17a2-4836-97d8-8a7777031f85) has changed to Interrupted`

**Expected behaviour:** Scanning tasks should reach 100% and switch to Done state.

**Comment by ZeNiRe** [comment]
Seems related to  https://github.com/greenbone/ospd-openvas/issues/335

**Comment by cfi-gb** [comment]
I'm closing this as a duplicate of https://github.com/greenbone/ospd-openvas/issues/335 for now. Please follow up there (some hints on debugging can be found there). It might be also possible that this was already fixed in https://github.com/greenbone/ospd-openvas/pull/390
