### ISSUE TITLE
[20.08] Missing scan configs

### ISSUE THREAD

**Issue by BustedSec** [greenbone/gvmd#1332]
In the web UI when I go to configure a scan the box labeled "scan config" is not populated. I ran into this once before on another install and the issue was with my feed.lock file not having read/write privs under the gvm user, fixing that and doing an nvt-sync fixed it. That is not the case this time. I can't figure it out. I've gone through logs, followed the troubleshooting steps outlined here (https://sadsloth.net/post/install-gvm-20_08-src-on-debian/). I've confirmed my feed user has the UUID associated properly,  I've been messing with it for days now. I'm running ubuntu 20.04, my NVTs are up to date, yet I do not have any options in the drop down box for feed config and I cannot start a scan because of it.

**Comment by cfi-gb** [comment]
Might be related: https://github.com/Atomicorp/gvm/issues/35

**Comment by cfi-gb** [comment]
Note that AFAIK gvmd is only able to successfully import the scan configs if it is able to connect to `ospd-openvas` and if `ospd-openvas` has a fully build NVT cache.

SecInfo -> NVTs needs to be filled and up to date, if not check things like https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#configure-the-default-ospd-scanner-socket-path or the logfiles of gvmd and ospd-openvas.

**Comment by mattmundell** [comment]
> Note that AFAIK gvmd is only able to successfully import the scan configs if it is able to connect to `ospd-openvas` and if `ospd-openvas` has a fully build NVT cache.

This should not be true any more.  Was changed in https://github.com/greenbone/gvmd/pull/1005.

**Comment by cfi-gb** [comment]
> > Note that AFAIK gvmd is only able to successfully import the scan configs if it is able to connect to `ospd-openvas` and if `ospd-openvas` has a fully build NVT cache.
> 
> This should not be true any more. Was changed in #1005.

Note sure about that, because the user here is reporting missing scan configs and he has no VTs in SecInfo > NVTs:

https://community.greenbone.net/t/how-to-manually-import-scan-config-from-cli/7239/14

**Comment by cfi-gb** [comment]
The missing scan configs from the user posted at the community portal was fixed by correctly configuring redis so that ospd-openvas is correctly listening on the socket gvmd is expecting it:

https://community.greenbone.net/t/how-to-manually-import-scan-config-from-cli/7239/18
