### ISSUE TITLE
[20.08] - Newly created users cannot change their passwords

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1367]
**Greenbone Vulnerability Manager 20.08.0~git-3276b8ff-gvmd-20.08
GIT revision 3276b8ff-gvmd-20.08
Manager DB revision 233
Greenbone Security Assistant 20.08.0~git-a7ed27e98-gsa-20.08
Operating System: Linux Mint 19.3 64 bits**

Note: This happened after migrating DB from GCE 11 to GCE 20.08

Current behaviour: Newly created users , members of the built in group "User" cannot change their passwords. They automatically get the following error:

![image](https://user-images.githubusercontent.com/48824957/100594546-1c1ff000-32fa-11eb-8376-75ac9c11e820.png)
![image](https://user-images.githubusercontent.com/48824957/100597996-6e631000-32fe-11eb-92c5-48f8945764d3.png)

Expected behaviour: Users should be able to change their passwords

**Comment by mattmundell** [comment]
I saw this with an older version of GSA 20.08, but when I updated to 20.08.0~git-a7ed27e98-gsa-20.08 it went away.

**Comment by y0urself** [comment]
If this still occures in the latest version please recreate the issue.
