### ISSUE TITLE
Hosts specification using CIDR notation fails, error message is not indicative to identify the culprit

### ISSUE THREAD

**Issue by alinuxexpert** [greenbone/gvmd#1382]
I am running the latest GSM TRIAL as a virtual appliance (using VirtualBox, following the official documentation). I am trying to specify a "New Target". My intention is to scan my home network. Thus, as "Hosts", I specify: "192.168.0.0/16" using the CIDR notation.

Expected behaviour: The target is created covering the specified IP range.

Actual behaviour: I receive the error message: "Error in host specification".

I'm not sure if this is a bug or a feature. I assume that the specified IP range is too large. However, I did not find any documentation saying how large the IP range may be. Also the error message is not helpful at all. As a user, the error message does not indicate what I might have done wrong. If the IP range is too large, then the error message should state exactly that.

![image](https://user-images.githubusercontent.com/8017305/102727442-f51b7380-4325-11eb-96ac-c21eadc74c5f.png)

**Comment by mattmundell** [comment]
This is supposed to give a "Host specification exceeds maximum number of hosts" error.

But e75b59d65981b0685e1f15e1a5f6a9e5507f3c1e changed gvmd to use openvas_hosts_new_with_max, which no longer differentiates between that error and others.

I'll add it to the backlog.

**Comment by alinuxexpert** [comment]
Would be great if the error message would indicate the actual maximum number of hosts. Also if the official documentation would mention that figure. At least I couldn't find that information anywhere.

**Comment by cfi-gb** [comment]
```
$ gvmd --help
*snip*
  --max-ips-per-target=<number>                 Maximum number of IPs per target.
```

I guess this isn't explicitly mentioned in the documentation because users might overload their scanner too easily is scanning such huge ranges.

**Comment by mattmundell** [comment]
Max hosts is configurable with gvmd's `--max-ips-per-target`, by the way.

**Comment by mattmundell** [comment]
> I guess this isn't explicitly mentioned in the documentation because users might overload their scanner too easily if scanning such huge ranges within a single task.

Yes, sounds right.

**Comment by alinuxexpert** [comment]
That's very helpful, @cfi-gb & @mattmundell - thank you very much!

**Comment by aretsmarvin** [comment]
After setting --max-ips-per-target to a higher limit, it still doens't work for me.
Doest the "--max-ips-per-target" have a maximum value?

**Comment by cfi-gb** [comment]
@aretsmarvin Please try to avoid asking the same questions at multiple places. The community portal is preferred place for such usage questions, an answer might be given in the future here:

https://community.greenbone.net/t/is-there-a-reason-for-the-max-host-specification-limit/7952

Thanks for your understanding.

**Comment by y0urself** [comment]
https://github.com/greenbone/gvmd/issues/1566
