### ISSUE TITLE
[GVE 20.08]  scan reported an error exporting CSV format

### ISSUE THREAD

**Issue by aiaiduo** [greenbone/gvmd#1387]
### Expected behavior
I exported the scan report in CSV format, and the exported CSV report should be one record in a row
![image](https://user-images.githubusercontent.com/28044296/103192179-b59aeb80-4912-11eb-8f02-d1f0145ce63e.png)

### Actual behavior
I exported the scan report to CSV format. The exported CSV report is not one line of record, but several lines of one record, which is not conducive to vulnerability statistical analysis
![image](https://user-images.githubusercontent.com/28044296/103192207-cfd4c980-4912-11eb-9c2a-11c64b1f2134.png)

### Steps to reproduce

1.
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvas --version)

**gvm-libs:**

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by y0urself** [comment]
@aiaiduo can you give us more information? What versions did you use, how to reproduce this. We provide the issue template not without a reason.

**Comment by aiaiduo** [comment]
OK，THS! Let me try again！
