### ISSUE TITLE
ldaps via 636 not usable / Feature Request?

### ISSUE THREAD

**Issue by jchnbckr** [greenbone/gvmd#1394]
I configured the ldap authentication and it fails

Our LDAP Server is only reachable via 636 using SSL

### Expected behavior
- Connect Server via Port 636 using ldaps with ssl

### Actual behavior
- only using ldap with start tls on port 389
- not configurable

### Steps to reproduce
1. enable ldap auth
2. using a ldap server with only open port 636 ldaps

### GVM versions

GSM 20.08.6

### Environment

**Operating system:**

### Logfiles
gvmd from live log

Jan 20 xxx gvmd[24811]: StartTLS failed, trying to establish ldaps connection.
Jan 20 xxx gvmd[24811]: LDAP authentication failure: Can't contact LDAP server.
Jan 20 xxx gvmd[24811]: Authentication failure for 'YYYYYYY' from unix_socket

**Comment by cfi-gb** [comment]
GVM supports both, LDAP via StartTLS on port 389 and LDAPS on port 636 as documented here:

> The GSM uses either the command StartTLS via LDAP on port 389 or SSL/TLS via LDAPS on port 636.
> https://docs.greenbone.net/GSM-Manual/gos-20.08/en/web-interface-access.html#ldap-with-ssl-tls

and shown in the message as well:

> Jan 20 xxx gvmd[24811]: StartTLS failed, trying to establish ldaps connection.

Basically it first tries StartTLS and if that connection doesn't work it falls back to LDAPS.

As this is most likely a configuration problem i'm closing this issue as "Invalid" for now. Please review:

https://docs.greenbone.net/GSM-Manual/gos-20.08/en/web-interface-access.html#ldap-with-ssl-tls

While this is not fully covering a GSE setup (GVM build from source) not everything mentioned at the docs might be valid for your setup. If you need further assistance with the GSE/GVM specific setup please follow up with a posting at the community portal here to get further support:

https://community.greenbone.net/
