### ISSUE TITLE
Permanent ban for multiple setup is inappropriate

### ISSUE THREAD

**Issue by e2002e** [greenbone/gvmd#1423]
Hi, I was setting up gvm and lost my network connection, it happened several times among the fact that as a noob I broke the installation several times....
Can you not, in this case, temporarily block the ip (even being for a month...), banning it really inappropriate.... 
Thanks.

**Comment by cfi-gb** [comment]
Unfortunately the development team isn't responsible for such topics which are also out of the reach of that team so i'm closing this issue as invalid as it isn't a bug in the gvmd / manager.

Thanks for your understanding.

If you see there are any problems with the feed please post a topic here: https://community.greenbone.net/c/feed-services/14
