### ISSUE TITLE
gvmd tries to access non-existent lock-file (GVMD_RUN_DIR could point to non-existent path)

### ISSUE THREAD

**Issue by M-Golyani** [greenbone/gvmd#1424]
### Expected behavior
When running gvmd it uses a lock-file path that was hardcoded at the build time. The lock-file would be better to be provided via a command-line argument, or default to a system generic path (like /var/run/lock/...)
The lock I'm talking about is referred to as "gvm-checking" according to the source ([HERE](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/src/gvmd.c#L2218))
The function "[lockfile_lock_nb](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/src/utils.c#L621)" uses "[lock_internal](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/src/utils.c#L541)" which in turn [uses](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/src/utils.c#L553) GVM_RUN_DIR to obtain the path of the lock file.

GVM_RUN_DIR should point to the current running DIR IMHO. However, AFA I checked, it is [set to](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/CMakeLists.txt#L184) ${LOCALSTATEDIR}/run, and LOCALSTATEDIR [is set to](https://github.com/greenbone/gvmd/blob/0882f8664fe1fcef9f63bdbf7b9bd6e48d1c7bf8/CMakeLists.txt#L133) ${CMAKE_INSTALL_PREFIX}/var

That causes the issue, e.g. when you build the whole package under /tmp, and then move the build tree to some other location, at the run-time, gvmd still relies on the static /tmp/build-path to be present.

I expect gvmd to use some environment variable or a command-line option, or at least the relative path to the actual CURRENT RUNNING dir, and not rely on a statically set path during the build process.

### Actual behavior

gvmd tries to access a hardcoded, non-existent path that was present at the build-time but removed afterwards.

### Steps to reproduce

1. Compile the whole package from source into a specific directory using -DCMAKE_INSTALL_PREFIX=${BUILD_PATH} (e.g. /tmp/gvm/)
2. Copy the whole built tree into some other location (```# mv  /tmp/gvm  /opt/```)
3. Setup the required users (gvm), ...
4. ```su - gvm```
5. run: ```gvmd --get-scanners```

### GVM versions

**gsa:** (gsad --version)
Not applicable

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 20.08.1~git-df9da22ee-gvmd-20.08
GIT revision df9da22ee-gvmd-20.08
Manager DB revision 233
Copyright (C) 2009-2021 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas-scanner:** (openvas --version)
N/A
**gvm-libs:**
N/A
### Environment

**Operating system:**
Linux ____ 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

**Installation method / source:** 
source installation
### Logfiles
N/A

```
```

**Comment by tgurr** [comment]
The build system is already very flexible in this regard, for our Exherbo packages which are compiled in a different directory as well, we just pass:
```
-DGVM_RUN_DIR:PATH=/run/gvm
-DLOCALSTATEDIR:PATH=/var
```
which is a quite common way to do.

**Comment by bjoernricks** [comment]
Exactly. Just set the desired path during compile time via cmakes `-D` flags.
