### ISSUE TITLE
[21.4.0] crash very often at function init_manage_create_functions.cold.131

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#1516]
### Expected behavior

Running gvmd service   

### Actual behavior

The service will crash 

### Steps to reproduce

1. open the ui via gsa
2. wait some time 

### GVM versions

**gsa:**  21.04.0

**gvm:** 21.4.0

**openvas-scanner:** 21.4.0 

**gvm-libs:** 21.4.0

### Environment

**Operating system:** CentOS 8

**Installation method / source:**  git release

### Logfiles

On the gvmd log file no errors will shown, only in the gsa  log:

> lib   xml:MESSAGE:2021-05-10 07h20.01 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.01 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h20.01 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.01 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h20.02 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.02 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h20.02 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.02 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h20.05 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.05 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h20.05 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h20.05 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h21.29 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h21.29 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:MESSAGE:2021-05-10 07h21.29 CEST:3247:    Error: Error on line 1 char 1: Document was empty or contained only whitespace
> lib   xml:WARNING:2021-05-10 07h21.29 CEST:3247:    End error: Error on line 1 char 1: Document was empty or contained only whitespace

And in the PostgreSQL (see attachment)
[pgsql_log.txt](https://github.com/greenbone/gvmd/files/6449717/pgsql_log.txt)

**Comment by timopollmeier** [comment]
Can you give some information about the setup? Is this happening in a new one or one migrated from an older version? Was there anything like creating a task or starting a scan you did before gvmd started crashing?

What gave you the idea that the crash is happening in init_manage_create_functions?

**Comment by tuxmaster5000** [comment]
Hi @timopollmeier ,
the function name comes from the stack trace generated by abrt. This was the function from which the crash was triggered. But ofm curse the real source can be another function.
The systems was migrated  from every version to the next since  gvmd 8.0.

Before the crash happens, an scan was stared, which needs up to 48 hours to complete. Can this  be the problem, that long scans trigger the crash? At the time of the crash, the scan was marked in the openvas scanner log as finished, but in the gsa ui as running. And an gvmd sql process was running with 100% on one cpu core. 

When using only short scan ( up to 14 hours) I have never seen this problem.

**Comment by y0urself** [comment]
Closing as this is related to an old version.
