### ISSUE TITLE
Can't scan subnets with /16 netmask

### ISSUE THREAD

**Issue by veronicapr** [greenbone/gvmd#1566]
### Expected behavior

Possibility to scan entire subnets with /16 netmask. 

### Actual behavior

Error message "Error in host specification" when trying to add target subnet with a /16 netmask.
![image](https://user-images.githubusercontent.com/26189831/122252687-757cf480-cec3-11eb-9230-8b254e6bb1b5.png)

### Steps to reproduce

1. Go to greenbone.
2. Go to the target menu in the "Configuration" tab.
3. Add new target.
4.  Add hosts manually with a /16 netmask. 
5. "Error in host specification" error message at the top of the page

### GVM versions

**gsa:** (gsad --version) Greenbone Security Assistant 20.08.0

**gvm:** (gvmd --version) Greenbone Vulnerability Manager 20.08.0

**openvas-scanner:** (openvas --version) OpenVAS 20.8.0

**gvm-libs:** 20.8.0

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation) Ubuntu 16.04.7 LTS

### Logfiles

```
```

**Comment by y0urself** [comment]
Hi @veronicapr AFAIK this is no bug.

As referred [here](https://docs.greenbone.net/GSM-Manual/gos-20.08/en/scanning.html?highlight=target#creating-a-target) you can only create targets with a maximum of 4096 IPs. You are trying to create a Target that contains 65536 IPs.

**Comment by huornlmj** [comment]
https://github.com/greenbone/gvmd/issues/1382
