### ISSUE TITLE
[21.4.1] source code verification fails

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#1585]
LANG=C gpg --verify SOURCES/gvmd-21.4.1.tar.gz.asc
gpg: assuming signed data in 'SOURCES/gvmd-21.4.1.tar.gz'
gpg: Signature made Wed Jun 23 16:29:49 2021 CEST
gpg:                using RSA key 8AE4BE429B60A59B311C2E739823FAA60ED1E580
gpg: BAD signature from "Greenbone Community Feed integrity key" [unknown]

**Comment by y0urself** [comment]
Yes. We are aware of it.

**Comment by tuxmaster5000** [comment]
ok thanks.

**Comment by y0urself** [comment]
should be fixed.

**Comment by tuxmaster5000** [comment]
Yes all is ok :)
