### ISSUE TITLE
API Documentation incomplete

### ISSUE THREAD

**Issue by Dexus** [greenbone/gvmd#1614]
https://docs.greenbone.net/API/GMP/gmp-21.04.html

incomplete documentation on multiple parts. This will only be for one we found:

### Expected behavior

That the API match the output from GVMD.

### Actual behavior

There are missed some status types and more, I see that there are on different API calls the output match not the API docs.

### Steps to reproduce

1. Run get_tasks in a loop.
2. create and start some tasks
3. you will get some status "Queued" which is not documentated.

### GVM versions

**gsa:** (gsad --version) v21.4.1

**gvm:** (gvmd --version) v21.4.2

**openvas-scanner:** (openvas --version) v21.4.1

**gvm-libs:** v21.4.1

### Environment

**Operating system:** Alpine & Ubuntu

**Installation method / source:** (packages, source installation) source

**Comment by y0urself** [comment]
https://docs.greenbone.net/GSM-Manual/gos-21.04/en/scanning.html?highlight=queue#managing-tasks
https://docs.greenbone.net/GSM-Manual/gos-21.04/en/scanning.html?highlight=queue#starting-the-task

**Comment by Dexus** [comment]
https://docs.greenbone.net/API/GMP/gmp-21.04.html#type_task_status

There is that missing!
