### ISSUE TITLE
[21.4.1] error/unable to access trashcan after deleting items with another user (of the same group)

### ISSUE THREAD

**Issue by tgurr** [greenbone/gvmd#1654]
### Expected behavior

Being able to access/view/delete/restore items in trashcan.

### Actual behavior / Steps to reproduce

Error when accessing the trashcan.

![Screenshot_20210707_145553](https://user-images.githubusercontent.com/414984/124766079-e0f03a00-df36-11eb-8c78-646f6334786b.png)

### Steps to reproduce

1. have a group with two members having user roles
2. user.one member of the group creates a target & a task
3. user.two member of the group deletes the target & the task moving them to the trashcan
4. after the steps above neither of the two users is able to acess the trashcan anymore to finally remove (or restore) the items

A user not being a member of the group can access the (empty) trashcan just fine, in this care my user with the admin role is the initial "admin". However once I add that user to the group in question the user is **also** unable to acess the trashcan and gets the same GSA error posted above.

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.1~dev1
**gvm:** Greenbone Vulnerability Manager 21.4.2 / Manager DB revision 242
**openvas-scanner:** OpenVAS 21.4.1
**gvm-libs:** gvm-libs 21.4.1

### Environment

**Operating system:** `Linux exherbo 5.12.0 greenbone/gsa#1 SMP Thu Apr 29 14:22:53 CEST 2021 x86_64 GNU/Linux`
**Installation method / source:** Exherbo packages (source-based)

### Logfiles
gvmd.log:
```
event target:MESSAGE:2021-07-07 12h11.00 CEST:3907768: Target test (f6864f93-a630-454c-b5fa-a61faf34db96) has been created by user.one
event task:MESSAGE:2021-07-07 12h11.06 CEST:3908220: Status of task  (d6509788-bccb-4394-b5fb-aae7f4e3f2ea) has changed to New
event task:MESSAGE:2021-07-07 12h11.06 CEST:3908220: Task test (d6509788-bccb-4394-b5fb-aae7f4e3f2ea) has been created by user.one
[...]
event task:MESSAGE:2021-07-07 14h35.11 CEST:11255: Task test (d6509788-bccb-4394-b5fb-aae7f4e3f2ea) has been deleted by user.two
event target:MESSAGE:2021-07-07 14h35.21 CEST:11326: Target test (f6864f93-a630-454c-b5fa-a61faf34db96) has been deleted by user.two
```
Despite the error message from GSA about the "Failure to receive response from manager daemon." I have no further output in any of the logs.

**Comment by bjoernricks** [comment]
I suppose this is related to #1636

**Comment by tgurr** [comment]
@bjoernricks thanks, I can confirm that applying https://github.com/greenbone/gvmd/commit/238cf3bad30c485909ec57a702baeb166d8a7d3a & https://github.com/greenbone/gvmd/commit/ea48ce85ba557354c88469a1edf76c25b5ada051 lets me access the trashcan again.

**Comment by bjoernricks** [comment]
Good to know. Thanks for the feedback.
