### ISSUE TITLE
Scripts removed with last release

### ISSUE THREAD

**Issue by cri-hash** [greenbone/gvmd#1746]
After last release, with debian version ( gvm:debian-master-data-full), scripts like add-scanner.sh have been removed from the root of docker, so it's not possible to add an OpenVas Scanner. I could add this script locally, but I would ask if it's a bug or a developer's choice, and, in this case, where to find it now or what is the official way to add scanner now. Thanks

**Comment by y0urself** [comment]
We are currently not providing any docker files, nor the script you mentioned. You are probably using third-party scripts.
