### ISSUE TITLE
Failed to parse client XML: Command Unavailable - incorrect log level INFO

### ISSUE THREAD

**Issue by lisenet** [greenbone/gvmd#1893]
I checked the list of open issues but did not see one that would reference this issue, hence opening. Feel free to close it if you're aware of a duplicate.

The gvmd log file `/var/log/gvm/gvmd.log` has a lot of entries like this:

```
md    gmp:   INFO:2022-12-15 19h32.41 UTC:245595:    Failed to parse client XML: Command Unavailable
```
It makes it difficult to track errors when a failure is marked as INFO and not an ERROR.

### Expected behavior

Logging level set to ERROR.

### Actual behavior

Logging level set to INFO.

### Steps to reproduce

Standard `gvmd` installation from Atomic repo (not built form source).

### GVM versions

**gsa:** (gsad --version) 
Greenbone Security Assistant 22.04.0

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 22.4.0~dev1
Manager DB revision 250

**openvas-scanner:** (openvas --version)
OpenVAS 22.4.0
gvm-libs 22.4.0

**gvm-libs:**
gvm-libs-22.4.0-26633.el8.art.x86_64

### Environment

**Operating system:**

Linux openvas 4.18.0-372.16.1.el8_6.0.1.x86_64 #1 SMP Thu Jul 14 21:39:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Rocky Linux release 8.6 (Green Obsidian)

**Installation method / source:** (packages, source installation)

Atomic repo.

### Logfiles

```
$ tail -n1 /var/log/gvm/gvmd.log
md    gmp:   INFO:2022-12-16 19h32.41 UTC:245595:    Failed to parse client XML: Command Unavailable
```

**Comment by cfi-gb** [comment]
This actually should have been indeed already handled in #1852 / #1853 and is awaiting to be included in the next gvmd release.

**Comment by bjoernricks** [comment]
As @cfi-gb wrote this is already fixed and will be included in the next release. The release can be expected in January. Additionally you can ignore that message until then.
