### ISSUE TITLE
CVE report has no host result

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gvmd#1894]
### Expected behavior

When exporting an CVE report, the file should contain information regaring the host and it's detected CVE's ext.

### Actual behavior

When we export an CVE report it holds the index and the hosts but no reult of the host is shown.

NVT export works just fine and holds all the exprected information.

```
2 Results per Host
2.1 1.1.1.2
Host scan start Tue Jun 29 12:00:19 2021 UTC
Host scan end Tue Jun 29 12:00:21 2021 UTC
Service (Port) Threat Level
2 RESULTS PER HOST 3
2.2 1.1.1.3
Host scan start Tue Jun 29 12:00:50 2021 UTC
Host scan end Tue Jun 29 12:00:51 2021 UTC
Service (Port) Threat Level
2.3 1.1.1.4
Host scan start Tue Jun 29 12:00:48 2021 UTC
Host scan end Tue Jun 29 12:00:50 2021 UTC
Service (Port) Threat Level
```

All filters are reset at it's default.

### Steps to reproduce

Not exactly sure when this bug is introduced, I lately have done a lot of rebuilds.

### GVM versions
Greenbone Security Assistant 21.4.1~dev1
Greenbone Vulnerability Manager 21.4.2~git-09bdb532f-HEAD
GIT revision 09bdb532f-HEAD
Manager DB revision 242
OpenVAS 21.4.1~git-81c6a4e8-HEAD
GIT revision ~git-81c6a4e8-HEAD
gvm-libs 21.4.1~git-f10b1be1-HEAD

### Environment

**Operating system:**
Linux ic-az1-sec01 5.4.0-77-generic 86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

### Logfiles
There are no log entries creted during the export.

**Comment by BasvanH** [comment]
@bjoernricks, is this going to get some attention?

**Comment by timopollmeier** [comment]
I've addressed the issue in the PDF report format itself. The fix is currently awaiting review and should be available in the feed a few days after it has been approved.
