### ISSUE TITLE
[7.0.2] SQL Warning when verify the CVE scanner via gsa

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvmd#19]
When the function for verifying the CVE scanner is called, an SQL warning will thrown:

> md manage:WARNING:2018-02-14 11h46.14 UTC:9969: sql_close: attempt to close db with open statement(s)

**Comment by timopollmeier** [comment]
This should be fixed with the pull request #115 (#114 for master).

**Comment by mattmundell** [comment]
PR was merged, and no feedback in ages, so assuming fixed.
