### ISSUE TITLE
schedules - date/time problems

### ISSUE THREAD

**Issue by BarryGould** [greenbone/gvmd#1911]
Hi, there is a problem with the schedules...
My local time zone is PST/PDT (UTC-8). The (Kali) OS is set to PST/PDT and everything else is behaving as expected.
$ cat /etc/timezone
America/Los_Angeles

In Dec 2022, I created a schedule in OpenVAS to run 
every 3rd Wed at 12:00 AM EST/EDT (UTC-5)
(note that 12:00AM and 12:01AM behave the same here)

It worked in December and January, and it _should_ run tonight, but instead OpenVAS is saying it will run NEXT MONTH. 

(At least I'd expect it to run next week in the worst case. And oddly, next month will potentially have the same issue as the 2nd Tuesday is _again_ adj. to 3rd Wed, yet it says it will run.)
If I hadn't double-checked the task, we'd have missed our scan window for the month, leading to a compliance failure.

WORKAROUND:
change the schedule to 5AM UTC instead of 12AM EST/EDT.
This appears to work; says will run tonight. But this workaround shouldn't be necessary.

$ openvas --version
OpenVAS 21.4.4
gvm-libs 21.4.4

$ cat /etc/timezone
America/Los_Angeles

$ lsb_release -a
Description:    Kali GNU/Linux Rolling
Release:        2022.3

Thanks!

**Comment by 4D617274696E** [comment]
Note: I have created an internal tracking issue for this problem at GEA-114.

**Comment by mattmundell** [comment]
Thanks for the report.
I've fixed the time in the 'Next Run' column in GSA in greenbone/gsa/pull/3818.
This column is calculated by the web fronted, so I believe your task will have run anyway. I set up a similar environment with the same dates in a VM and the task started OK. See the PR for the list of steps I took.
