### ISSUE TITLE
Stale global_current_report causes subsequent gvmd requests to fail

### ISSUE THREAD

**Issue by khesterproton** [greenbone/gvmd#1979]
### Expected behavior

To be able to make multiple requests from the python-gvm client; acting on different targets and tasks. 
Sometimes reusing the same connection; sometimes creating a new one.

### Actual behavior

It looks like requests are failing because some gvmd process state (global_current_report) isn't cleared between requests.

### Steps to reproduce

Using the python-gvm client, start a CVE scanner task (connecting via TLSConnection to 9390).

Make a subsequent request to start an OpenVAS scanner task. The request fails, leaving the task in the New state.

### GVM versions

**gsa:** Greenbone Security Assistant 22.04.1

**gvm:** Greenbone Vulnerability Manager 22.4.2, Manager DB revision 250

**openvas-scanner:** OpenVAS 22.4.1

**gvm-libs:** gvm-libs 22.4.4

### Environment

**Operating system:** Linux 5.15.0-1030-aws #34-Ubuntu SMP Mon Jan 23 20:13:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

**Installation method / source:** https://greenbone.github.io/docs/latest/22.4/source-build/index.html

Python 3.9.16
python-gvm==23.2.0

### Logfiles

gvmd.log (with some of my debugging)
```
event task:MESSAGE:2023-05-01 09h15.30 UTC:28171: Status of task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - OpenVAS (9be77392-d252-4ab5-a5b6-9d0a4c1f0217) has changed to Done
event task:MESSAGE:2023-05-01 09h15.47 UTC:117652: Status of task  (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has changed to New
event task:MESSAGE:2023-05-01 09h15.47 UTC:117652: Task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - CVE (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has been created by admin
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 1, global_current_report: 0
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 4, creating UUID
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 5, UUID report_id: 2f7493e2-4081-4ca2-9177-31a45ab80fda
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 7, creating report
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 8, new global_current_report: 24
md manage:WARNING:2023-05-01 09h15.48 UTC:117652: create_current_report() 9, report scheduled, all good
event task:MESSAGE:2023-05-01 09h15.48 UTC:117652: Status of task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - CVE (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has changed to Requested
event task:MESSAGE:2023-05-01 09h15.48 UTC:117652: Task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - CVE (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has been requested to start by admin
event task:MESSAGE:2023-05-01 09h15.48 UTC:117689: Status of task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - CVE (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has changed to Running
event task:MESSAGE:2023-05-01 09h15.48 UTC:117689: Status of task 2023-05-01 08:03:36.663820 - 7507 - 1.1.1.1 - CVE (c176bae0-4bba-4afb-a2a9-dde82bf33da7) has changed to Done
...
event port_list:MESSAGE:2023-05-01 09h27.24 UTC:117652: Port List T:25,465,587 (eeb67496-d135-4560-819e-4d10a7ed0146) has been created by admin
event target:MESSAGE:2023-05-01 09h27.24 UTC:117652: Target 2023-05-01 09:27:24.175111 - 7506 - 3.3.3.3 (8765541c-0923-4ae2-8140-53735c8ccad3) has been created by admin
event task:MESSAGE:2023-05-01 09h27.25 UTC:117652: Status of task  (d3178774-99ef-4eb9-9c33-9d6b68e0ab0b) has changed to New
event task:MESSAGE:2023-05-01 09h27.25 UTC:117652: Task 2023-05-01 09:27:24.175111 - 7506 - 3.3.3.3 - Discovery (d3178774-99ef-4eb9-9c33-9d6b68e0ab0b) has been created by admin
md manage:WARNING:2023-05-01 09h27.26 UTC:117652: run_osp_scan_get_report() calling create_current_report(), from: 0, resume_report: 0
md manage:WARNING:2023-05-01 09h27.26 UTC:117652: create_current_report() 1, global_current_report: 24
md manage:WARNING:2023-05-01 09h27.26 UTC:117652: create_current_report() 2, have global_current_report so returning -1
md manage:WARNING:2023-05-01 09h27.26 UTC:117652: run_osp_scan_get_report() create report failed, returning -1
md manage:WARNING:2023-05-01 09h27.26 UTC:117652: Couldn't fork OSP scan handler
event task:MESSAGE:2023-05-01 09h27.26 UTC:117652: Task 2023-05-01 09:27:24.175111 - 7506 - 3.3.3.3 - Discovery (d3178774-99ef-4eb9-9c33-9d6b68e0ab0b) could not be started by admin
```

### More information

I'd originally posted this as a forum question here: https://forum.greenbone.net/t/couldnt-fork-osp-scan-handler-error-upgrading-to-22-4/14597 

This is a shortened version of that post.

We're upgrading a 21.4 Greenbone installation (from a PPA) to 22.4 (built from source). While testing the new server I kept seeing start_task() requests fail with “Couldn’t fork OSP scan handler” errors in the gvmd.log.

My observation is that the gvmd processes are long-lived on the server. I haven’t looked at the code that spawns/manages these but assume this is working as intended. I.e. if a client disconnects the server process remains and is available for handling future client requests.

The errors occur on gvmd processes that previously handled a “CVE scanner” request. I have not seen the error after an “OpenVAS scanner” request.

I noticed that in manage.c the CVE code path doesn’t seem to zero out the global_current_report and current_scanner_task globals in the parent process. 

Below is a comparison of fork_osp_scan_handler() and fork_cve_scan_handler() (with edits and comments).

```
fork_osp_scan_handler (...)
{
  ...
  if (run_osp_scan_get_report (task, from, &report_id))
    return -1;

  // run_osp_scan_get_report() has called create_current_report() 
  // and set global_current_report in the parent process
  ...
  switch (fork ())
    {
      case 0:
        // Child
        ...
        break;
      case -1:
        /* Parent, failed to fork. */
        global_current_report = 0;
        current_scanner_task = 0;
        ...
        return -9;
      default:
        /* Parent, successfully forked. */
        global_current_report = 0;
        current_scanner_task = 0;
        ...
        return 0;
    }
  ...
  // Child process continues, performs scan and exit()s
}
```
```
fork_cve_scan_handler (...)
{
  ...
  if (create_current_report (task, &report_id, TASK_STATUS_REQUESTED))
    return -1;

  // create_current_report() has set global_current_report in the parent process
  ...
  switch (fork ())
    {
      case 0:
        // Child
        ...
      case -1:
        /* Parent, failed to fork. */
        global_current_report = (report_t) 0;
        // Does NOT null out current_scanner_task
        ...
        return -9;
      default:
        /* Parent, successfully forked. */
        // Does NOT null out global_current_report or current_scanner_task
        return 0;
    }
  ...
  // Child process continues, creates CVE report and exit()s
}
```

So I added these lines to the `case -1` and `default` branches of the `fork_cve_scan_handler()` switch.
```
global_current_report = 0;
current_scanner_task = 0;
```

It seems reasonable that the CVE and OSP code would need to clean up in the same way.

This _has_ seemed to solve the “Couldn’t fork OSP scan handler” errors I was seeing.

I'm inclined to think I must be using the GMP incorrectly or have something on the server configured wrong (or have screwed up the build, etc). If this is a bug I don't why it would suddenly appear for me. The exact code in question doesn't seem to have changed between 21.4 and 22.4.

But that said, the code change seems to have fixed it for me!

**Comment by y0urself** [comment]
Please feel free to create a PR and contribute your changes - they will then be tested. Thank you!

**Comment by khesterproton** [comment]
> Please feel free to create a PR and contribute your changes - they will then be tested. Thank you!

I will do that. Thanks!
