### ISSUE TITLE
Upgrader la version de gvm de 22.4.0 à 22.4.1 

### ISSUE THREAD

**Issue by francktsopzang237** [greenbone/gvmd#1994]
![342f5b1bc26c4e5f25b2ecc0cb9e8ef05d9e196f](https://github.com/greenbone/gvmd/assets/54401325/b0b84f4a-7653-483e-9a1b-1fcc2c9ccae1)

**Comment by cfi-gb** [comment]
Hello,

please use https://forum.greenbone.net/ for support requests as stated in e.g.
- https://github.com/greenbone/gvmd#support
- the issue template described at `Before reporting an issue please:`

this question / how to handle this message has been discussed / outlined there quite some time and should be easy to find via the search function.
