### ISSUE TITLE
sql_exec_internal failed in check_osp_result_exists()

### ISSUE THREAD

**Issue by dvppvd** [greenbone/gvmd#2006]
### Expected behavior
No error.

### Actual behavior

The function [check_osp_result_exists()](https://github.com/greenbone/gvmd/blob/b846590e7d45af6765ed015743b185f6bb6cd1ec/src/manage_sql.c#L29005) generate a SQL statement without check for missing value for the `severity` and `qod` attributes (maybe because of NVT timed out), which may result in sql_exec_internal failed.

### Steps to reproduce
1. Run a scan.
2. Check the logs.

### GVM versions
**gvm:** 22.4.3~dev1

### Logfiles

```
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sql_exec_internal: PQexec failed: ERROR:  syntax error at or near "and"
LINE 1: ....'    and port = 'general/tcp' and severity =     and qod = ...
                                                             ^
 (7)
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sql_exec_internal: SQL: SELECT EXISTS (SELECT * FROM results   WHERE report = 137 and hash_value = '405b3db5584b5e7eb7e40fc8b0b99732'    and host = '127.0.0.1' and hostname = ''    and type = 'Error Message' and description = 'NVT timed out after 320 seconds.'    and port = 'general/tcp' and severity =     and qod =  and path = '' );
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sql_x: sql_exec_internal failed
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: manage_cleanup_process_error: Error exit, setting running task to Interrupted
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sql_exec_internal: PQexec failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (7)
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sql_exec_internal: SQL: UPDATE reports SET scan_run_status = 13 WHERE id = 137;
md manage:WARNING:2023-06-05 17h58.16 UTC:31409: sqlv: sql_exec_internal failed
```

**Comment by sed-ats** [comment]
I get the same error

when running several tasks in which there are several hosts
in version gvmd 22.4.2 everything worked fine
**GVM versions**
Greenbone Vulnerability Manager 22.5.1
Manager DB revision 254

```
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: sql_exec_internal: SQL: SELECT EXISTS (SELECT * FROM results   WHERE report = 1474 and hash_value = '021f7f15fcd0f3c6cec682bb841c8f83'    and host = '10.10.19.17' and hostname = ''    and type = 'Error Message' and description = 'NVT timed out after 60 seconds.'    and port = 'general/tcp' and severity = '-3.0'    and qod = '' and path = '' );
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: sql_x: sql_exec_internal failed
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: manage_cleanup_process_error: Error exit, setting running task to Interrupted
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: sql_exec_internal: PQexec failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (7)
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: sql_exec_internal: SQL: UPDATE reports SET scan_run_status = 13 WHERE id = 1474;
md manage:WARNING:2023-07-11 13h15.22 UTC:1975299: sqlv: sql_exec_internal failed
md   main:WARNING:2023-07-11 15h39.41 UTC:2225933: write_to_client_unix: failed to write to client: Broken pipe
md   main:WARNING:2023-07-11 15h43.28 UTC:2226423: write_to_client_unix: failed to write to client: Broken pipe
```

**Comment by dg1rtf** [comment]
Same in src/manage_sql.c: check_osp_result_exists
md manage:WARNING:2023-07-12 08h54.24 UTC:428416: sql_exec_internal: PQexec failed: ERROR:  invalid input syntax for type integer: ""
LINE 1: ... and port = '' and severity = '-3.0'    and qod = '' and pat...
                                                             ^
 (7)
md manage:WARNING:2023-07-12 08h54.24 UTC:428416: sql_exec_internal: SQL: SELECT EXISTS (SELECT * FROM results   WHERE report = 423 and hash_value = '424e3e36a9b25bc7f5953f591e683215'    and host = '' and hostname = ''    and type = 'Error Message' and description = 'Scan process Failure'    and port = '' and severity = '-3.0'    and qod = '' and path = '' );
md manage:WARNING:2023-07-12 08h54.24 UTC:428416: sql_x: sql_exec_internal failed
md manage:WARNING:2023-07-12 08h54.24 UTC:428416: manage_cleanup_process_error: Error exit, setting running task to Interrupted
