### ISSUE TITLE
gvmd fail to compile

### ISSUE THREAD

**Issue by montjoie** [greenbone/gvmd#2017]
I started a fresh install on debian 11.
I grabbed all branch stable git repositories
I successfully built and installed gvm-libs, openvas-smb, openvas but gvmd fail to build with:
-- Found Git: /usr/bin/git (found version "2.30.2") 
[  0%] Built target revisiontag
[  0%] Building C object src/CMakeFiles/gvmd.dir/manage_sql_nvts.c.o
/home/bob/gvmd/src/manage_sql_nvts.c: In function ‘update_preferences_from_vt’:
/home/bob/gvmd/src/manage_sql_nvts.c:1247:15: error: implicit declaration of function ‘print_element_to_string’; did you mean ‘print_date_to_string’? [-Werror=implicit-function-declaration]
 1247 |               print_element_to_string (param, debug);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
      |               print_date_to_string
/home/bob/gvmd/src/manage_sql_nvts.c: In function ‘nvti_from_vt’:
/home/bob/gvmd/src/manage_sql_nvts.c:1334:3: error: implicit declaration of function ‘nvti_put_name’; did you mean ‘nvti_set_name’? [-Werror=implicit-function-declaration]
 1334 |   nvti_put_name (nvti, element_text (name));
      |   ^~~~~~~~~~~~~
      |   nvti_set_name
/home/bob/gvmd/src/manage_sql_nvts.c:1338:5: error: implicit declaration of function ‘nvti_put_summary’; did you mean ‘nvti_set_summary’? [-Werror=implicit-function-declaration]
 1338 |     nvti_put_summary (nvti, element_text (summary));
      |     ^~~~~~~~~~~~~~~~
      |     nvti_set_summary
/home/bob/gvmd/src/manage_sql_nvts.c:1342:5: error: implicit declaration of function ‘nvti_put_insight’; did you mean ‘nvti_set_insight’? [-Werror=implicit-function-declaration]
 1342 |     nvti_put_insight (nvti, element_text (insight));
      |     ^~~~~~~~~~~~~~~~
      |     nvti_set_insight
/home/bob/gvmd/src/manage_sql_nvts.c:1346:5: error: implicit declaration of function ‘nvti_put_affected’; did you mean ‘nvti_set_affected’? [-Werror=implicit-function-declaration]
 1346 |     nvti_put_affected (nvti, element_text (affected));
      |     ^~~~~~~~~~~~~~~~~
      |     nvti_set_affected
/home/bob/gvmd/src/manage_sql_nvts.c:1350:5: error: implicit declaration of function ‘nvti_put_impact’; did you mean ‘nvti_set_impact’? [-Werror=implicit-function-declaration]
 1350 |     nvti_put_impact (nvti, element_text (impact));
      |     ^~~~~~~~~~~~~~~
      |     nvti_set_impact
/home/bob/gvmd/src/manage_sql_nvts.c:1375:7: error: implicit declaration of function ‘nvti_put_detection’; did you mean ‘nvti_set_detection’? [-Werror=implicit-function-declaration]
 1375 |       nvti_put_detection (nvti, element_text (detection));
      |       ^~~~~~~~~~~~~~~~~~
      |       nvti_set_detection
/home/bob/gvmd/src/manage_sql_nvts.c:1395:7: error: implicit declaration of function ‘nvti_put_solution’; did you mean ‘nvti_set_solution’? [-Werror=implicit-function-declaration]
 1395 |       nvti_put_solution (nvti, element_text (solution));
      |       ^~~~~~~~~~~~~~~~~
      |       nvti_set_solution
/home/bob/gvmd/src/manage_sql_nvts.c:1556:3: error: implicit declaration of function ‘nvti_put_family’; did you mean ‘nvti_set_family’? [-Werror=implicit-function-declaration]
 1556 |   nvti_put_family (nvti, element_text (family));
      |   ^~~~~~~~~~~~~~~
      |   nvti_set_family
/home/bob/gvmd/src/manage_sql_nvts.c: In function ‘update_nvt_cache_osp’:
/home/bob/gvmd/src/manage_sql_nvts.c:1968:7: error: implicit declaration of function ‘osp_get_vts_ext_str’; did you mean ‘osp_get_vts_ext’? [-Werror=implicit-function-declaration]
 1968 |   if (osp_get_vts_ext_str (connection, get_vts_opts, &str))
      |       ^~~~~~~~~~~~~~~~~~~
      |       osp_get_vts_ext
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/gvmd.dir/build.make:290: src/CMakeFiles/gvmd.dir/manage_sql_nvts.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:175: src/CMakeFiles/gvmd.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

**Comment by bjoernricks** [comment]
Hi,

please don't use branches to build gvmd and use the latest tag instead. stable is abandoned and main may contain changes not ready for end users.

**Comment by bjoernricks** [comment]
Same for the other repos btw. Please build from the latest tag or use the release files instead.

**Comment by montjoie** [comment]
I have nearly the same issue when following the official build guide from https://greenbone.github.io/docs/latest/22.4/source-build/index.html

**Comment by bjoernricks** [comment]
Just tried to reproduce your issue with a fresh `debian:bullseye-slim` docker container. Used all steps from https://greenbone.github.io/docs/latest/22.4/source-build/index.html until the gvmd build and it works fine (for bullseye you just need to install postgresql-server-dev-13 instead of postgresql-server-dev-15).

![grafik](https://github.com/greenbone/gvmd/assets/897575/77c1048e-2626-4abd-9656-c91056486704)

**Comment by bjoernricks** [comment]
If you can reproduce the issue in a clean docker container feel free to reopen it again.
