### ISSUE TITLE
Email Alert message with `attach report` option does not allow use of $i for full report text

### ISSUE THREAD

**Issue by syspect-sec** [greenbone/gvmd#2072]
### Expected behavior

According to the manual, the `$i` dynamic report information variable should work with both 
`include` and `attach report` reporting options [according to the docs here](https://docs.greenbone.net/GSM-Manual/gos-21.04/en/scanning.html?highlight=alerts#fig-alert-new:~:text=The%20content%20of%20the%20e%2Dmail%20message%20can%20be%20edited%20for%20both%2C%20the%20included%20and%20the%20attached%20report.%20For%20the%20message%20the%20following%20placeholders%20can%20be%20used%3A)

### Actual behavior

Although the `$i` variable is honoured with the `include report` option it is not honoured for the `attach report` option.
In the `attach report` case, the emailed report does not include the full report text into the email body. 
This impacts all installations tested so far:

* Ubuntu source code install
* Ubuntu Docker containers
* Kali Linux native GVM installation
* CentOS source code install

### Steps to reproduce

1. Configure Greenbone with SMTP configuration (can use [this tutorial here](https://forum.greenbone.net/t/configuring-smtp-for-alerts/15446))
2. Create an alert and select Email method with the `attach report` option 
3. Select any report attachment option
4. Add the `$i` variable to the report text configuration input textbox
5. Trigger a test of the alert

### Environment

**Operating system:**

This impacts all installations tested so far:

* Ubuntu source code install
* Ubuntu Docker containers
* Kali Linux native GVM installation
* CentOS source code install

### Logfiles

No relevant output in the logs.

**Comment by mattmundell** [comment]
Thanks for the clear description.

The `$i` variable is intentionally only supported for the `include report` option.

I guess the doc you linked has been updated since you reported, it currently says:
```
    $i: the report text or list of SecInfo objects (only if including the report/list).
```
"**only if including**" refers to the `include report` option.
