### ISSUE TITLE
Create nsis_found() function for NSIS/EXE LSC generation

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/gvmd#212]
#112 and #207 had removed the alien_found() call from the NSIS/EXE LSC generation as the usage of alien was dropped in master and alien wasn't used at all for NSIS.

As a replacement a new function nsis_found() similar to the dropped alien_found() could be implemented like suggested in https://github.com/greenbone/gvm/pull/207#pullrequestreview-165482455

**Comment by y0urself** [comment]
Closing as this is a very old issue and probably not related anymore.
