### ISSUE TITLE
Could not connect to scanner on Kali 2024.1(Virtual Box)

### ISSUE THREAD

**Issue by Bosson015** [greenbone/gvmd#2246]
### Expected behavior

After installing gvm and subsequent configuration using the gvm-setup script and checking using gvm-chek-setup, I got a positive result. I went to the Greenbone web interface. I checked Feed status, everything was OK. You can start a test scan.

### Actual behavior

I created a task via Scans--->Tasks--->Task Wizard to quickly create a task. To my regret, I received a 0% interrupt with the error Could not connect to Scanner. 

![error](https://github.com/greenbone/gvmd/assets/117225231/e636a032-4183-422b-9a8f-55ef2d7878b5)

I checked the Scanner on the web interface via Configuration--->Scanners--->Verify Scanner and got this...

![error2](https://github.com/greenbone/gvmd/assets/117225231/4b4fc1da-7bea-413b-b02d-f3829783874d)

In the gvmd.log file I noticed that the scanner is accessing a socket called ospd-openvas.sock. Having checked the directory /run/ospd/, I found that the socket file names did not match between the actual value of the name and the name in the log file.

![logfile](https://github.com/greenbone/gvmd/assets/117225231/9fa80264-67e9-4c19-ae93-9a29a8f77bce)
![2024-07-01_22-25-47](https://github.com/greenbone/gvmd/assets/117225231/a9ed8320-2e7b-4ad9-aab5-66b27b57deb5)

The solution is as follows...

### Steps to reproduce

1. Go to the /run/ospd/ directory `cd /run/ospd` 
2. Rename the socket file `mv ospd.sock ospd-openvas.sock`
3. Next, edit the configuration file ospd-openvas.conf. This is necessary because after the first two steps the scanning started, but after receiving the Running status it ended with an error. In the log file gvmd.log I found that the Scanner now wants to connect to a socket named ospd.sock, that is, by the old name. Therefore, open the /etc/gvm/ospd-openvas.conf file with any editor and change the unix_socket line as in the screenshot
![confFile](https://github.com/greenbone/gvmd/assets/117225231/8712e0dc-ea39-44d7-bb8b-8bd5990b749c)

4. If gvm was running before, then stop it `gvm-stop`
5. Be sure to restart the computer in any case, even if gvm was not running
6. I hope, like me, after the work done, you will get a positive result like here
![fix1](https://github.com/greenbone/gvmd/assets/117225231/15fe2f97-4e81-4ad2-843a-f5826fae905d)

![fix2](https://github.com/greenbone/gvmd/assets/117225231/01af9fde-889b-4507-be31-cbb288c2cef5)

### GVM versions

**gsa:** Greenbone Security Assistant 22.9.1~git

**gvm:** Greenbone Vulnerability Manager 23.6.2

**openvas-scanner:** OpenVAS 23.4.1

**gvm-libs:** 22.10.0

### Environment

**Operating system:**  Linux kali 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-05-17) x86_64 GNU/Linux

**Installation method / source:** (packages, source installation) apt-get install gvm

### Logfiles

```
```

**Comment by cfi-gb** [comment]
@Bosson015 Kali packages as well as `gvm-check-setup` and `gvm-setup` are not provided / maintained by Greenbone. Could you thus please close this issue and raise a new one over here for the Kali maintainers: https://bugs.kali.org

**Comment by cfi-gb** [comment]
Refs to the relevant Bug reports:
- https://bugs.kali.org/view.php?id=8812
- https://bugs.kali.org/view.php?id=8813
