### ISSUE TITLE
Setup master-sensor in docker

### ISSUE THREAD

**Issue by jeagercoder** [greenbone/gvmd#2301]
Hello, thank you for your hard work. can someone tell me how to setup master-sensor in docker?

**Comment by cfi-gb** [comment]
There is the following mentioned in https://raw.githubusercontent.com/greenbone/gvmd/refs/heads/main/.github/ISSUE_TEMPLATE/bug-report.md which should apply here:

> Before reporting an issue please:
>
> 1. Be aware that this is not a support forum. If your issue is rather a question than a bug report, please use our community forum at https://community.greenbone.net/c/gse instead.

The link seems to be currently dead but you should be able to find an adequate category to place the question at https://forum.greenbone.net/
