### ISSUE TITLE
openvasmd will not tell the truth about scanners and more!

### ISSUE THREAD

**Issue by asmaack** [greenbone/gvmd#242]
After an update (on release branches) of python-gvm, gvm-tools, gvm-libs, gvmd, openvas-scanner, gasd, it looks like openvasmd is not returning valid answers to gvm-cli, gsa/gsad and gvm-pyshell.

Command "openvasmd --get-scanners" will return valid data on openvassd scanners, whereas command 'gvm-cli socket -c --xml "<get_scanners/>"' returns data about 0 (zero) scanners .

Same goes for gsa, which show an empty scanners page (Configuration > Scanners). 

And, "gvm-pyshell socket -c -i" gmp.get_scanners() also returns zero scanner count 
`<scanner_count>0<filtered>0</filtered><page>0</page></scanner_count>`

To reproduce:
Query for active scanners with openvasmd (openvasmd.log output included):

```
$ sudo openvasmd --get-scanners
08b69003-5fc2-4037-a479-93b440211c73  OpenVAS Default
6acd0832-df90-11e4-b9d5-28d24461215b  CVE

md   main:MESSAGE:2018-11-08 15h29.41 utc:15493:    OpenVAS Manager version 7.0.4 (GIT revision 26b72751-openvas-manager-7.0) (DB revision 184)
md manage:   INFO:2018-11-08 15h29.41 utc:15493:    Getting scanners.
```

However, same query over "gvm-cli socket --xml" will receive 0 scanners (openvasmd.log output included):

```
$ gvm-cli socket -c --xml "<get_scanners/>"
<get_scanners_response status="200" status_text="OK"><filters id=""><term>first=1 rows=1000 sort=name</term><keywords><keyword><column>first</column><relation>=</relation><value>1</value></keyword><keyword><column>rows</column><relation>=</relation><value>1000</value></keyword><keyword><column>sort</column><relation>=</relation><value>name</value></keyword></keywords></filters><sort><field>name<order>ascending</order></field></sort><scanners start="1" max="1000"/>**<scanner_count>0<filtered>0</filtered><page>0</page></scanner_count>**</get_scanners_response>

md   main:  DEBUG:2018-11-08 15h32.34 utc:15498:    Serving OMP.
md   main:  DEBUG:2018-11-08 15h32.34 utc:15498: <= client  Input may contain password, suppressed.
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: -> client: <authenticate_response status="200" status_text="OK"><role>Admin</role><timezone>UTC</timezone><severity>nist</severity></authenticate_response>
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: => client  144 bytes
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: => client  done
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: <= client  "<get_scanners/>"
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: -> client: <get_scanners_response status="200" status_text="OK">
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: -> client: <filters id=""><term>first=1 rows=1000 sort=name</term><keywords><keyword><column>first</column><relation>=</relation><value>1</value></keyword><keyword><column>rows</column><relation>=</relation><value>1000</value></keyword><keyword><column>sort</column><relation>=</relation><value>name</value></keyword></keywords></filters><sort><field>name<order>ascending</order></field></sort><scanners start="1" max="1000"/><scanner_count>0<filtered>0</filtered><page>0</page></scanner_count></get_scanners_response>
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: => client  560 bytes
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498: => client  done
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498:    EOF reading from client.
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498:    Cleaning up.
md   main:  DEBUG:2018-11-08 15h32.34 UTC:15498:    Exiting.
```

Now, reverting back to a commit from Sep. 14th, and rebuilding, all will work normally:

```
~/gvmd$ git checkout 210d8d0d2634a2918879c108320d16845d52b447
~/gvmd$ rm -r build
~/gvmd$ mkdir build
~/gvmd$ cd build
~/gvmd$ cmake ..
~/gvmd$ make
~/gvmd$ sudo make install
~/gvmd$ make rebuild_cache
~/gvmd$ sudo killall openvasmd
~/gvmd$ sudo /usr/local/sbin/openvasmd --unix-socket=/usr/local/var/run/gvmd.sock

~$ gvm-cli socket -c --xml "<get_scanners/>"
<get_scanners_response status="200" status_text="OK"><scanner id="6acd0832-df90-11e4-b9d5-28d24461215b"><owner><name></name></owner><name>CVE</name><comment></comment><creation_time>2018-11-06T20:14:28Z</creation_time><modification_time>2018-11-06T20:14:28Z</modification_time><writable>1</writable><in_use>0</in_use><permissions></permissions><user_tags><count>0</count></user_tags><host></host><port>0</port><type>3</type><ca_pub></ca_pub><credential id=""><name></name><trash>0</trash></credential></scanner><scanner id="08b69003-5fc2-4037-a479-93b440211c73"><owner><name></name></owner><name>OpenVAS Default</name><comment></comment><creation_time>2018-11-06T20:14:28Z</creation_time><modification_time>2018-11-06T20:14:28Z</modification_time><writable>1</writable><in_use>0</in_use><permissions></permissions><user_tags><count>0</count></user_tags><host>/usr/local/var/run/openvassd.sock</host><port>0</port><type>2</type><ca_pub></ca_pub><credential id=""><name></name><trash>0</trash></credential></scanner><filters id=""><term>first=1 rows=1000 sort=name</term><keywords><keyword><column>first</column><relation>=</relation><value>1</value></keyword><keyword><column>rows</column><relation>=</relation><value>1000</value></keyword><keyword><column>sort</column><relation>=</relation><value>name</value></keyword></keywords></filters><sort><field>name<order>ascending</order></field></sort><scanners start="1" max="1000"/><scanner_count>0<filtered>0</filtered><page>2</page></scanner_count></get_scanners_response>

```

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.4
GIT revision 293cf3c7f-gsa-7.0

**gvm:** (gvmd --version) / openvasmd --version
~$ openvasmd --version
OpenVAS Manager 7.0.4
GIT revision 26b72751-openvas-manager-7.0
Manager DB revision 184

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3

**gvm-libs:**
git log:
commit db1306c117df6dde5324b75cb4517b2382a5ba98 (HEAD -> openvas-libraries-9.0, origin/openvas-libraries-9.0)

### Environment
**Operating system:**
$ uname -a
Linux sknr1 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 18.04.1 LTS

**Installation method / source:** (packages, source installation)
From source.

**Comment by asmaack** [comment]
Same error seems to be encountered for other commands as well, see:

$ sudo openvasmd --get-users
**admin**

$ gvm-cli socket -c --xml "<get_users/>"
<get_users_response status="200" status_text="OK"><filters id=""><term>first=1 rows=1000 sort=name</term><keywords><keyword><column>first</column><relation>=</relation><value>1</value></keyword><keyword><column>rows</column><relation>=</relation><value>1000</value></keyword><keyword><column>sort</column><relation>=</relation><value>name</value></keyword></keywords></filters><sort><field>name<order>ascending</order></field></sort><users start="1" max="1000"/>**<user_count>0<filtered>0</filtered><page>0</page></user_count>**</get_users_response>

**Comment by mattmundell** [comment]
Should be solved with greenbone/gvmd/pull/243

**Comment by asmaack** [comment]
Confirmed fix, works like a charm now!

I suppose, in a perfect world this shouldn't have happened on a release branch :-)
Or is openvas-manager-7.0 not in feature freeze?

**Comment by bjoernricks** [comment]
Yes it is. But sometimes we have to fix important customer issues which lead to such backports. We are trying to improve the situation for future releases.
