### ISSUE TITLE
sql_exec_internal: sqlite3_step failed: interrupted

### ISSUE THREAD

**Issue by cgjue** [greenbone/gvmd#289]
### Steps to reproduce
1.
2.
3.

### GVM versions
**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```

```

**Comment by cfi-gb** [comment]
@cgjue Please provide all information from the issue template. I'm closing this issue as "invalid" for now, please ping me once all information about your issue have been provided and we can re-open the issue again.
