### ISSUE TITLE
Credential username can be created with underscore character but credential can't be used

### ISSUE THREAD

**Issue by NicholasLeader** [greenbone/gvmd#312]
### Expected behavior
I would like to use my AD (active directory) account which contains an underscore, to performed credentialed (authenticated) scans.

Minimally I should be prevented from entering the credentials and saving it to avoid confusion if special characters are truly not allowed.

If special characters are not allowed (unlike other tools that leverage AD credentials) than I'll need to change my service account username or possible create another account.

### Current behavior
I'm allowed to create the credentials with no error, but the authenticated scan fails (without disclosing why in the PDF report). 
Going back to edit the password for the credential, I'm then warned that I can't use special characters in the username. May be related to: https://github.com/greenbone/gvmd/issues/185

### Steps to reproduce
1. Created username with underscore character in the credentials section of OpenVAS. 'Configuration' --> 'Credentials' --> 'new credential' button. save it.
2. try to edit credential (receive warning about credential containing special characters.

### GVM versions
**gsa:** (gsad --version)
7.0.3

**gvm:** (gvmd --version)
'command not found'
**openvas-scanner:** (openvassd --version)
5.1.3

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:** Kali Linux on VMware workstation 12

**Installation method / source:** (packages, source installation)
Download from Offensive security (VMware tools version of Kali)

### Logfiles

```

```

**Comment by bjoernricks** [comment]
>  if special characters are truly not allowed

That's not an easy task as it sounds first. Due to local policies and different operating systems some usernames might be valid on one system but not on the other. There is no username rule that fits for all systems.

We are aware of these problems and are thinking about something like "test these credentials to login into this system" functionality. But this is in an early stage and will take some time.

**Comment by bjoernricks** [comment]
>  Related: How do you specify an (AD Windows) domain if you don't allow special characters?
> 
> e.g. '@' or '/'
> 
> Reference: https://joedsweb.wordpress.com/2017/02/12/openvas-windows-local-security-checks/comment-page-1/#comment-42

Please use https://community.greenbone.net/ for this question. That's our forum for getting help about more setup specific issues.

**Comment by cfi-gb** [comment]
As pointed out in the [community thread](https://community.greenbone.net/t/error-when-updating-password-on-credentials-used-in-authenticated-scans/958) the underscore as well as ``@``, ``/`` or ``.`` seems to be supported / allowed with the PR https://github.com/greenbone/gvmd/pull/59 and will be shipped with the next openvas-manager release.
