### ISSUE TITLE
openvas use masscan only , thats had no data found

### ISSUE THREAD

**Issue by cgjue** [greenbone/gvmd#318]
### Expected behavior
masscan could be used and the found data could be inserted into database
### Current behavior
masscan could be used but the found data could not be inserted into database
### Steps to reproduce
1. scan config  -->choose port scanner--> choose masscan only
2. choose target one ip
3. creat one target

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 8.0+beta3
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta2
Manager DB revision 200
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0+beta3
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```

```

**Comment by cfi-gb** [comment]
Hi,

this is unlikely a bug in the manager code (masscan is "wrapped" around in NASL code) and more likely either a mis-configuration (e.g. masscan isn't found within the path) or gb_masscan.nasl isn't compatible with the masscan version you're using.

I'm closing this issue as "invalid" for now, please create a new thread with some more details (e.g. environment, is masscan installed and similar) at https://community.greenbone.net/c/gse

**Comment by cgjue** [comment]
i use openvas-nasl to debug the gb_masscan.nasl ,found that the gb_masscan.nasl could be called and the masscan found data, and "scanner_add_port(proto:proto, port:port);" in gb_masscan.nasl called。So I think the data flow went to gvmd。

**Comment by cgjue** [comment]
why the data found could not be inserted into database?  I opened the database log =ALL, that made me can see all sql data. 
complared with use host discovery ，I found many inserted sql data in database log，but use masscan coul not found。

**Comment by cgjue** [comment]
you can make a simple test。it's easy to reproduce. Don't just think...

**Comment by cfi-gb** [comment]
The manager (gvmd) isn't using the results of the portscanner at all. Please use the mentioned category in the community portal if you want to discuss and understand this topic.

**Comment by cgjue** [comment]
so, can you help me with this question? Is it becasuse i make a wrong config of openvas scan config? Or Is it I should ask openvas-scanner for help?

**Comment by cfi-gb** [comment]
> so, can you help me with this question?

As advised in the issue template:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.

as well as in https://github.com/greenbone/gvmd/issues/318#issuecomment-451900645 please ask your questions in https://community.greenbone.net/c/gse

**Comment by cgjue** [comment]
thank you all the same
