### ISSUE TITLE
error: implicit declaration of function ‘gvm_auth_tear_down’

### ISSUE THREAD

**Issue by M1chael** [greenbone/gvmd#384]
### Expected behavior
make compiles sources

### Current behavior
make returns error: 
```
gvmd.c:921:3: error: implicit declaration of function ‘gvm_auth_tear_down’ [-Werror=implicit-function-declaration]
   gvm_auth_tear_down ();
   ^~~~~~~~~~~~~~~~~~
```

### Steps to reproduce
1. `cd gvmd-8.0-beta2`
2. `mkdir build`
3. `cd build`
4. `cmake ..`
5. `make`

### GVM versions
gvmd-8.0-beta2

### Environment
**Operating system:** Debian GNU/Linux 9

**Installation method / source:** source installation

### Logfiles
```
[  3%] Building C object src/CMakeFiles/gvmd-sqlite.dir/gvmd.c.o
/root/install/openvas10/gvmd-8.0-beta2/src/gvmd.c: In function ‘cleanup’:
/root/install/openvas10/gvmd-8.0-beta2/src/gvmd.c:921:3: error: implicit declaration of function ‘gvm_auth_tear_down’ [-Werror=implicit-function-declaration]
   gvm_auth_tear_down ();
   ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
src/CMakeFiles/gvmd-sqlite.dir/build.make:62: recipe for target 'src/CMakeFiles/gvmd-sqlite.dir/gvmd.c.o' failed
make[2]: *** [src/CMakeFiles/gvmd-sqlite.dir/gvmd.c.o] Error 1
CMakeFiles/Makefile2:154: recipe for target 'src/CMakeFiles/gvmd-sqlite.dir/all' failed
make[1]: *** [src/CMakeFiles/gvmd-sqlite.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by cfi-gb** [comment]
Thanks for your report. Please try to always use a current version (e.g. Beta3 is current and was released a few days ago). In this newer version the gvm_auth_tear_down() function isn't called anymore in the cleanup function:

https://github.com/greenbone/gvmd/blob/v8.0%2Bbeta3/src/gvmd.c#L891-L913

I'm closing this for now as this specific build issue shouldn't happen anymore. Once you are on Beta3 and other build issues are showing up please create a new issue.
