### ISSUE TITLE
[beta3] Build faills

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#385]
The beta3 build fails with:

> In file included from /usr/include/string.h:638:0,
>                  from /usr/include/glib-2.0/glib/gtestutils.h:30,
>                  from /usr/include/glib-2.0/glib.h:82,
>                  from /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_base.h:29,
>                  from /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.h:29,
>                  from /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c:33:
> In function 'memset',
>     inlined from 'create_ticket_reset' at /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c:351:10:
> /usr/include/bits/string3.h:84:3: error: call to __builtin___memset_chk will always overflow destination buffer [-Werror]
>    return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
>    ^
> In function 'memset',
>     inlined from 'modify_ticket_reset' at /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c:635:10:
> /usr/include/bits/string3.h:84:3: error: call to __builtin___memset_chk will always overflow destination buffer [-Werror]
>    return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
>    ^
> In function 'memset',
>     inlined from 'create_ticket_start' at /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c:366:10:
> /usr/include/bits/string3.h:84:3: error: call to __builtin___memset_chk will always overflow destination buffer [-Werror]
>    return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
>    ^
> In function 'memset',
>     inlined from 'modify_ticket_start' at /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c:650:10:
> /usr/include/bits/string3.h:84:3: error: call to __builtin___memset_chk will always overflow destination buffer [-Werror]
>    return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
>    ^
> cc1: all warnings being treated as errors
> make[2]: *** [src/CMakeFiles/gvmd-pg.dir/gmp_tickets.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c: In function 'escalate_2':
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c:12810:24: error: 'filter' may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                    body = alert_message_print (message, event, event_data,
>                         ^
> cc1: all warnings being treated as errors
> make[2]: *** [src/CMakeFiles/gvmd-pg.dir/gmp_tickets.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c: In function 'escalate_2':
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c:12810:24: error: 'filter' may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                    body = alert_message_print (message, event, event_data,
>                         ^
> cc1: all warnings being treated as errors
> make[2]: *** [src/CMakeFiles/gvmd-pg.dir/manage_sql.c.o] Error 1
> make[2]: Leaving directory `/builddir/build/BUILD/gvmd-8.0-beta3'
> make[1]: Leaving directory `/builddir/build/BUILD/gvmd-8.0-beta3'
> make[1]: *** [src/CMakeFiles/gvmd-pg.dir/all] Error 2
> make: *** [all] Error 2

OS: CentOS 7.6

**Comment by tuxmaster5000** [comment]
Thanks, the patch will fix the first error.
But the second will occurs again.

> cd /builddir/build/BUILD/gvmd-8.0-beta3/src && /usr/lib64/ccache/cc -DCACERT=\"/var/lib/greenbone/CA/cacert.pem\" -DCA_DIR=\"/var/lib/greenbone/gvmd/trusted_certs\" -DCLIENTCERT=\"/var/lib/greenbone/CA/clientcert.pem\" -DCLIENTKEY=\"/var/lib/greenbone/private/CA/clientkey.pem\" -DGMP_VERSION=\"8.0\" -DGVMD_CERT_DATABASE_VERSION=6 -DGVMD_DATABASE_VERSION=205 -DGVMD_DATA_DIR=\"/usr/share/gvm/gvmd\" -DGVMD_SCAP_DATABASE_VERSION=15 -DGVMD_STATE_DIR=\"/var/lib/greenbone/gvmd\" -DGVMD_VERSION=\"8.0+beta4\" -DGVM_CERT_DATA_DIR=\"/var/lib/greenbone/cert-data\" -DGVM_CERT_RES_DIR=\"/usr/share/gvm/cert\" -DGVM_DATA_DIR=\"/usr/share/gvm\" -DGVM_LIB_INSTALL_DIR=\"/usr/lib64/gvmd\" -DGVM_LOG_DIR=\"/var/log/greenbone/gvmd\" -DGVM_NVT_DIR=\"/usr/var/lib/openvas/plugins/\" -DGVM_OS_NAME=\"Linux-3.10.0-957.5.1.el7.x86_64\" -DGVM_RUN_DIR=\"/run/greenbone\" -DGVM_SCAP_DATA_DIR=\"/var/lib/greenbone/scap-data\" -DGVM_SCAP_RES_DIR=\"/usr/share/gvm/scap\" -DGVM_SQLITE_SLEEP_MAX=0 -DGVM_STATE_DIR=\"/var/lib/greenbone\" -DGVM_SYSCONF_DIR=\"/etc/gvm\" -DPREFIX=\"/usr\" -DSBINDIR=\"/usr/sbin\" -DSCANNERCERT=\"/var/lib/greenbone/CA/servercert.pem\" -DSCANNERKEY=\"/var/lib/greenbone/private/CA/serverkey.pem\" -I/usr/include/gvm -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gvm-helper -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall -D_BSD_SOURCE -D_ISOC99_SOURCE -D_SVID_SOURCE -D_DEFAULT_SOURCE -D_FILE_OFFSET_BITS=64 -g -Werror -Wshadow     -Wredundant-decls -o CMakeFiles/gvmd-pg.dir/gmp_tickets.c.o   -c /builddir/build/BUILD/gvmd-8.0-beta3/src/gmp_tickets.c
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c: In function 'escalate_2':
> /builddir/build/BUILD/gvmd-8.0-beta3/src/manage_sql.c:12810:24: error: 'filter' may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                    body = alert_message_print (message, event, event_data,
>                         ^
> cc1: all warnings being treated as errors
> make[2]: *** [src/CMakeFiles/gvmd-pg.dir/manage_sql.c.o] Error 1
> make[2]: Leaving directory `/builddir/build/BUILD/gvmd-8.0-beta3'
> make[1]: *** [src/CMakeFiles/gvmd-pg.dir/all] Error 2
> make[1]: Leaving directory `/builddir/build/BUILD/gvmd-8.0-beta3'
> make: *** [all] Error 2
>

**Comment by tuxmaster5000** [comment]
As I understand the code, the function alert_message_print itself will check the state of the filter variable.

**Comment by mattmundell** [comment]
Didn't see the second one.  Does https://github.com/greenbone/gvmd/pull/399 solve it for you?

**Comment by tuxmaster5000** [comment]
Yes, https://github.com/greenbone/gvmd/pull/399 will fix it. I have not seen here any reference to it.
