### ISSUE TITLE
PostgreSQL error due to usage of reserved keyword

### ISSUE THREAD

**Issue by bascouba** [greenbone/gvmd#429]
### Expected behavior

Lists of tasks displaying severity and no PostgreSQL error

### Current behavior

Tasks are working fine, I can see results of reports but every task is showing internal error as level of severity for last report.

### Steps to reproduce
1. Start a task and wait for it to end
2. Catch logs at /var/log/postgresql/postgresql-9.6-main.log

### Logs

> 2019-03-08 17:35:03.833 CET [2773] root@tasks ERREUR: l’opérateur n’existe pas : name = integer au caractère 84
> 2019-03-08 17:35:03.833 CET [2773] root@tasks ASTUCE : Aucun opérateur ne correspond au nom donné et aux types d’arguments.
> Vous devez ajouter des conversions explicites de type.
> 2019-03-08 17:35:03.833 CET [2773] root@tasks INSTRUCTION : SELECT max(severity) FROM report_counts WHERE report = 8 AND override = 1 AND **user** = (SELECT id FROM users WHERE uuid = ‘cb9ea5dd-70da-410c-aa69-533dc138802b’) AND min_qod = 70 AND (end_time = 0 or end_time >= m_now ());

So I found out that the problem occurs when the keyword user is used because it's a reserved keyword and should not be used in data scheme.

When I enter manually in my database the following request, with "user" instead of user

> SELECT max(severity) FROM report_counts WHERE report = 8 AND override = 1 AND **“user”** = (SELECT id FROM users WHERE uuid = ‘cb9ea5dd-70da-410c-aa69-533dc138802b’) AND min_qod = 70 AND (end_time = 0 or end_time >= m_now ());

I have no error.

```
```

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
