### ISSUE TITLE
Export PDF - broken

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/gvmd#467]
### Expected behavior
PDF Export

### Actual behavior
does not show the result.

Scan:
![image](https://user-images.githubusercontent.com/17960988/53442629-8189d300-39e8-11e9-8f45-07ed5bdad684.png)

Broken PDF, error in the summary?
```
This document reports on the results of an automatic security scan. All dates are displayed using the timezone America/SaoP aulo00, whichisabbreviated“ − 0300.T hetaskwas“Scan − Samaritano −
AllV alids00.T hescanstartedatMonF eb2521 : 20 : 052019 − 03andendedatMonF eb2522 : 00 : 202019 −
03.T hereportf irstsummarisestheresultsfound.T hen, foreachhost, thereportdescribeseveryissuefound.P leaseconsidertheadvicegivenineachdescription, inordertorectif ytheissue.
```
![image](https://user-images.githubusercontent.com/17960988/53442471-1f30d280-39e8-11e9-9733-9d0b40befc8e.png)

![image](https://user-images.githubusercontent.com/17960988/53443892-7be1bc80-39eb-11e9-953e-9f9b170399fa.png)

Texlive Installed:
![image](https://user-images.githubusercontent.com/17960988/53442920-2efce680-39e9-11e9-9102-ffbb97767615.png)

### Steps to reproduce

1. export to PDF
2. 
3. 

### GVM versions

**gsa:** (gsad --version)
```
# gsad --version
Greenbone Security Assistant 9.0+alpha~git-4d71cc189-master
GIT revision 4d71cc189-master
```

**gvm:** (gvmd --version)
```
# gvmd --version
Greenbone Vulnerability Manager 9.0+alpha~git-b6d078e6-master
GIT revision b6d078e6-master
Manager DB revision 206
```

**openvas-scanner:** (openvassd --version)
```
# openvassd --version
OpenVAS Scanner 6.0+beta3
GIT revision 3e87367-master
```

**gvm-libs:**
git - checkout: 61ae9c01880fe120ad6f49c73c588a6c3927858f

### Environment

**Operating system:**

```
# cat /etc/debian_version
9.7
```
https://cloud.docker.com/u/dgiorgio/repository/docker/dgiorgio/openvas-source
tag: master-2.4.3

**Installation method / source:** (packages, source installation)

### Logfiles
No logs.

```
```

**Comment by bjoernricks** [comment]
I've moved this issue from gsa to gvmd because report formats are provided by gvmd.

**Comment by greatquux** [comment]
Also an issue with 9.0.0.
root@openvas:/# gvmd --version
Greenbone Vulnerability Manager 9.0.0
Manager DB revision 221

root@openvas:/etc/redis# dpkg -l | grep texlive
ii  texlive-base                           2017.20180305-1                                 all          TeX Live: Essential programs and files
ii  texlive-binaries                       2017.20170613.44572-8ubuntu0.1                  amd64        Binaries for TeX Live
ii  texlive-fonts-extra                    2017.20180305-2                                 all          TeX Live: Additional fonts
ii  texlive-fonts-extra-links              2017.20180305-2                                 all          TeX Live:
ii  texlive-fonts-recommended              2017.20180305-1                                 all          TeX Live: Recommended fonts
ii  texlive-latex-base                     2017.20180305-1                                 all          TeX Live: LaTeX fundamental packages
ii  texlive-latex-extra                    2017.20180305-2                                 all          TeX Live: LaTeX additional packages
ii  texlive-latex-recommended              2017.20180305-1                                 all          TeX Live: LaTeX recommended packages
ii  texlive-pictures                       2017.20180305-1                                 all          TeX Live: Graphics, pictures, diagrams

![image](https://user-images.githubusercontent.com/1655942/83022769-04d61200-9ffa-11ea-8b0b-8166ce543652.png)

**Comment by bjoernricks** [comment]
There is already a newer release 9.0.1. Maybe this is fixed in the release.

**Comment by greatquux** [comment]
I wound up compiling everything in gvm-11.0.1 (it would be nice to sync the version numbers of the components) and it does actually export the results now, though the Summary is still broken as above.  
Also, PDF export is kinda fragile... at first I got 0-byte PDF files despite having all fonts and scripts installed.  I had to to turn debugging mode on at level=128 just to see that the generate script couldn't overwrite a file /tmp/err.log because it was owned by nobody, once I removed it, PDF export worked.  Why can't we just have everything run as root again? :)

**Comment by bjoernricks** [comment]
> it would be nice to sync the version numbers of the components)

Of course. GVM 11 is the last version with this numbering scheme. The next version will use calendar versioning. This is already in place in all master branches of our components.

**Comment by acosonic** [comment]
For me, the problem resolved after installing missing fonts and imagemagick inside docker container running Ubuntu, which had gsa installed...

`apt install imagemagick texlive-fonts-recommended`

**Comment by Schadrac96** [comment]
Hello dear computer scientists, I congratulate you very much on this subject. As I read what you did, I thought to myself that you can help me. I just want to know if there is a possibility to automatically export the report of vulnerabilities detected by GVM? I am working on an automatic vulnerability correction solution with GVM and ANSIBLE.

**Comment by cfi-gb** [comment]
@Schadrac96 Please note that this issue tracker is used for reporting and tracking bugs in GVM and shouldn't be used to ask random usage questions (especially not in open issues completely unrelated to the asked question).

If you have questions on the usage of GVM or one of its components please raise your question at https://community.greenbone.net/

Thanks.

**Comment by bmomartins** [comment]
> For me, the problem resolved after installing missing fonts and imagemagick inside docker container running Ubuntu, which had gsa installed...
> 
> `apt install imagemagick texlive-fonts-recommended`

Worked for me, thanks!

**Comment by nigerninja** [comment]
Cross posting from [CVE report has no host result #3044](https://github.com/greenbone/gsa/issues/3044) as it seems the issued is not truly resolved.

Please any help resolving this? Dependencies / packages from [greenbone/gvmd#467](https://github.com/greenbone/gvmd/issues/467) are installed as well and other formats export properly, thanks.
````
gsad --version
Greenbone Security Assistant 21.4.4

gvmd --version
Greenbone Vulnerability Manager 21.4.5
Manager DB revision 242
Copyright (C) 2009-2021 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

cat /etc/debian_version
kali-rolling

cat /etc/*-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.1"
VERSION_ID="2022.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

dpkg -l | grep texlive
ii  texlive-base                                     2021.20220204-1                      all          TeX Live: Essential programs and files
ii  texlive-bibtex-extra                             2021.20220204-1                      all          TeX Live: BibTeX additional styles
ii  texlive-binaries                                 2021.20210626.59705-1                amd64        Binaries for TeX Live
ii  texlive-extra-utils                              2021.20220204-1                      all          TeX Live: TeX auxiliary programs
ii  texlive-font-utils                               2021.20220204-1                      all          TeX Live: Graphics and font utilities
ii  texlive-fonts-extra                              2021.20220204-1                      all          TeX Live: Additional fonts
ii  texlive-fonts-extra-doc                          2021.20220204-1                      all          TeX Live: Documentation files for texlive-fonts-extra
ii  texlive-fonts-extra-links                        2021.20220204-1                      all          TeX Live: Setup of fonts for TeX Live and search via kpathsea
ii  texlive-fonts-recommended                        2021.20220204-1                      all          TeX Live: Recommended fonts
ii  texlive-fonts-recommended-doc                    2021.20220204-1                      all          TeX Live: Documentation files for texlive-fonts-recommended
ii  texlive-formats-extra                            2021.20220204-1                      all          TeX Live: Additional formats
ii  texlive-full                                     2021.20220204-1                      all          TeX Live: metapackage pulling in all components of TeX Live
ii  texlive-games                                    2021.20220204-1                      all          TeX Live: Games typesetting
ii  texlive-humanities                               2021.20220204-1                      all          TeX Live: Humanities packages
ii  texlive-humanities-doc                           2021.20220204-1                      all          TeX Live: Documentation files for texlive-humanities
ii  texlive-lang-arabic                              2021.20220204-1                      all          TeX Live: Arabic
ii  texlive-lang-chinese                             2021.20220204-1                      all          TeX Live: Chinese
ii  texlive-lang-cjk                                 2021.20220204-1                      all          TeX Live: Chinese/Japanese/Korean (base)
ii  texlive-lang-cyrillic                            2021.20220204-1                      all          TeX Live: Cyrillic
ii  texlive-lang-czechslovak                         2021.20220204-1                      all          TeX Live: Czech/Slovak
ii  texlive-lang-english                             2021.20220204-1                      all          TeX Live: US and UK English
ii  texlive-lang-european                            2021.20220204-1                      all          TeX Live: Other European languages
ii  texlive-lang-french                              2021.20220204-1                      all          TeX Live: French
ii  texlive-lang-german                              2021.20220204-1                      all          TeX Live: German
ii  texlive-lang-greek                               2021.20220204-1                      all          TeX Live: Greek
ii  texlive-lang-italian                             2021.20220204-1                      all          TeX Live: Italian
ii  texlive-lang-japanese                            2021.20220204-1                      all          TeX Live: Japanese
ii  texlive-lang-korean                              2021.20220204-1                      all          TeX Live: Korean
ii  texlive-lang-other                               2021.20220204-1                      all          TeX Live: Other languages
ii  texlive-lang-polish                              2021.20220204-1                      all          TeX Live: Polish
ii  texlive-lang-portuguese                          2021.20220204-1                      all          TeX Live: Portuguese
ii  texlive-lang-spanish                             2021.20220204-1                      all          TeX Live: Spanish
ii  texlive-latex-base                               2021.20220204-1                      all          TeX Live: LaTeX fundamental packages
ii  texlive-latex-base-doc                           2021.20220204-1                      all          TeX Live: Documentation files for texlive-latex-base
ii  texlive-latex-extra                              2021.20220204-1                      all          TeX Live: LaTeX additional packages
ii  texlive-latex-extra-doc                          2021.20220204-1                      all          TeX Live: Documentation files for texlive-latex-extra
ii  texlive-latex-recommended                        2021.20220204-1                      all          TeX Live: LaTeX recommended packages
ii  texlive-latex-recommended-doc                    2021.20220204-1                      all          TeX Live: Documentation files for texlive-latex-recommended
ii  texlive-luatex                                   2021.20220204-1                      all          TeX Live: LuaTeX packages
ii  texlive-metapost                                 2021.20220204-1                      all          TeX Live: MetaPost and Metafont packages
ii  texlive-metapost-doc                             2021.20220204-1                      all          TeX Live: Documentation files for texlive-metapost
ii  texlive-music                                    2021.20220204-1                      all          TeX Live: Music packages
ii  texlive-pictures                                 2021.20220204-1                      all          TeX Live: Graphics, pictures, diagrams
ii  texlive-pictures-doc                             2021.20220204-1                      all          TeX Live: Documentation files for texlive-pictures
ii  texlive-plain-generic                            2021.20220204-1                      all          TeX Live: Plain (La)TeX packages
ii  texlive-pstricks                                 2021.20220204-1                      all          TeX Live: PSTricks
ii  texlive-pstricks-doc                             2021.20220204-1                      all          TeX Live: Documentation files for texlive-pstricks
ii  texlive-publishers                               2021.20220204-1                      all          TeX Live: Publisher styles, theses, etc.
ii  texlive-publishers-doc                           2021.20220204-1                      all          TeX Live: Documentation files for texlive-publishers
ii  texlive-science                                  2021.20220204-1                      all          TeX Live: Mathematics, natural sciences, computer science packages
ii  texlive-science-doc                              2021.20220204-1                      all          TeX Live: Documentation files for texlive-science
ii  texlive-xetex                                    2021.20220204-1                      all          TeX Live: XeTeX and packages


````
