### ISSUE TITLE
wrong endings for your releases

### ISSUE THREAD

**Issue by shibumi** [greenbone/gvmd#494]
Hi,
Your release signatures have a wrong file ending. They are named with the following pattern: `gvmd-$version.tar.gz.sig.asc`. The ending `sig.asc` breaks our package build system on Arch Linux. Could you please rename this either to `tar.gz.sig` or `tar.gz.asc`? I think `tar.gz.sig.asc` is not necessary... thanks a lot.

**Comment by bjoernricks** [comment]
I would use the `tar.gz.asc` ending. It's more obvious with `.asc` that our signature is a gpg signature.

**Comment by shibumi** [comment]
@bjoernricks totally fine. Just be aware to not add both endings :)

**Comment by timopollmeier** [comment]
It looks like the ".asc" suffix is added automatically when I try to rename the file to have the ".sig" suffix like previous releases.
I've now removed the extra ".sig" part.
