### ISSUE TITLE
gvmd.c:114:10: fatal error: gitrevision.h: No such file or directory

### ISSUE THREAD

**Issue by mafli77** [greenbone/gvmd#518]
I got an error when I tried to build and make the current master of gvmd:

 cmake -DBACKEND=POSTGRESQL .. 

..
[  0%] Built target revisiontag
[  2%] Building C object src/CMakeFiles/gvmd-pg.dir/gvmd.c.o
/usr/local/src/gse10/gvmd-master/src/gvmd.c:114:10: fatal error: gitrevision.h: No such file or directory
 #include "gitrevision.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/gvmd-pg.dir/build.make:62: recipe for target 'src/CMakeFiles/gvmd-pg.dir/gvmd.c.o' failed
make[2]: *** [src/CMakeFiles/gvmd-pg.dir/gvmd.c.o] Error 1
CMakeFiles/Makefile2:126: recipe for target 'src/CMakeFiles/gvmd-pg.dir/all' failed
make[1]: *** [src/CMakeFiles/gvmd-pg.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

When I delete the line "#include gitrevision.h" everything works well.

**Comment by cikk3y** [comment]
that happened to me too, when i downloaded the zip from github. There is the .git directory missing.
So if you clone gvmd with **git clone**, there are files like .git/refs/heads/master or .git/HEAD with the specific commit hashes (f.i. ed0ac7ec6b23652600f8702c2efbc69a8ecef7cd) that need to be included to generate gitrevision.h

**Comment by tuxmaster5000** [comment]
Same for 9.0.0.

**Comment by timopollmeier** [comment]
This should be fixed in the PR #792.
Since the release wasn't officially announced yet, I've re-created the release tag with the fix included.
