### ISSUE TITLE
Filters not consistent within Results view

### ISSUE THREAD

**Issue by uwedisch** [greenbone/gvmd#521]
Hello,

if the filter "apply_overrides=1 min_qod=70 autofp=0 levels=hml first=1 rows=50 sort-reverse=created not tag~result" is used on the Results view the filter is not consistently used on the page.

Please see screenshots:

![Bildschirmfoto vom 2019-05-04 07-58-23](https://user-images.githubusercontent.com/24267159/57174738-9d27b480-6e43-11e9-9f10-c4668322fd0e.png)

![Bildschirmfoto vom 2019-05-04 08-07-50](https://user-images.githubusercontent.com/24267159/57174762-d5c78e00-6e43-11e9-9792-0f078fe6ce7b.png)

It's obvious that the filter part "not tag~result" isn't interpreted consistently at the whole Results view.

Expected count of complete filter is 46. Count of filter without "not tag~result" is 62.

This is GSA 7.0.3 on Kali rolling. All updates are applied.

**Comment by mattmundell** [comment]
I can't reproduce with master or 8.0.  Also tried master with SQLite.  @bjoernricks, maybe PM some details tomorrow?

**Comment by bjoernricks** [comment]
i've used the exact filter mentioned here * "apply_overrides=1 min_qod=70 autofp=0 levels=hml first=1 rows=50 sort-reverse=created not tag~result"* and got different result counts in the dashboards and the list. The filter has been send correctly to gsad (and should therefore be forwarded 1:1 to gvmd).

**Comment by mattmundell** [comment]
The case seen by @bjoernricks is fixed for me by #548.

Not sure if that's the same as yours, @uwedisch.  Could you test?

**Comment by uwedisch** [comment]
Sorry, the system is sticking to version of Kali Rolling and can't switch to manual install.

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
