### ISSUE TITLE
[8.0.0] mail from on email alert not respected.

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#524]
### Expected behavior
That the From value is used when the mail will created

### Current behavior
The from field is filled with: <gvmd@hostname>

### Steps to reproduce
1. create an alert with email method.
2. test it.

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 8.0.0~git

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0.0

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0.0

**gvm-libs:**
10.0.0

**openvas-smb:**
1.0.5

### Environment
**Operating system:**
CentOS 7.6

**Installation method / source:** (packages, source installation)
From git

### Logfiles
Postfix
```
postfix/qmgr[9229]: 32A601505: from=<gvmd@XXXXXX>, size=899, nrcpt=1 (queue active)
```

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
