### ISSUE TITLE
[8.0.0] greenbone-certdata-sync/greenbone-scapdata-sync log rsync output to the stdout

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#538]
When the script is running via cron, the status is logged to syslog as expected.
But the output of the rsync call is logged to stdout, so on every cron run, an mail is generated.
Sample output:

> 
> Greenbone community feed server - http://feed.community.greenbone.net/
> This service is hosted by Greenbone Networks - http://www.greenbone.net/
> 
> All transactions are logged.
> 
> If you have any questions, please use the Greenbone community portal. 
> See https://community.greenbone.net for details.
> 
> By using this service you agree to our terms and conditions.
> 
> Only one sync per time, otherwise the source ip will be temporarily blocked.
> 
> receiving incremental file list
> timestamp
> 
>               0   0%    0.00kB/s    0:00:00  
>              13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)
> 
> sent 43 bytes  received 114 bytes  104.67 bytes/sec
> total size is 13  speedup is 0.08

Expected:
That only in case of an error something will logged to stderr or syslog.

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.

**Comment by tuxmaster5000** [comment]
Same for current version
