### ISSUE TITLE
[8.0.0] gvm-portnames-update has no quiete option

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#539]
When the script is runnig via cron, then on every run an mail is generated, because it will report the result to stdout.
Sample output:

> Updated 11518 entries.

**Comment by cfi-gb** [comment]
This script is gone since GVMd of current master and 20.08 with https://github.com/greenbone/gvmd/pull/1041. Closing here as there is unlikely that the older variants of this script will get any updates.
