### ISSUE TITLE
[8.0.0] Unable to import an S/MIME certificate

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#540]
### Expected behavior
That I can import an S/MIME certificate for email encryption.

### Current behavior
The error "Erroneous Certificate." will shown.

### Steps to reproduce
1. create new credentials 
2. set type to S/MIME
3. select the file

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 8.0.0~git

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0.0

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0.0

**gvm-libs:**
10.0.0

**openvas-smb:**
1.0.5

### Environment
**Operating system:**
CentoOS 7.6

**Installation method / source:** (packages, source installation)
Git

### Logfiles
gvmd.log:
util gpgme:WARNING:2019-05-10 09h09.06 CEST:13257: gvm_gpg_import_from_string: key_str is not the expected type:  expected: 34, got 35

**Comment by cfi-gb** [comment]
If this was a X.509 cert then https://github.com/greenbone/gvmd/pull/573 (Backport in https://github.com/greenbone/gvmd/pull/551) should have added support for this cert type.

**Comment by tuxmaster5000** [comment]
I have added both patches (gvm-libs and gvmd).
But it will not work. Now I only get other error:

> util gpgme:WARNING:2019-06-03 09h25.42 CEST:10710: gvm_gpg_import_many_types_from_string: Import failed: End of file

For gvmd I have used the patch 551 and 231 for the gvm-lib.

**Comment by cfi-gb** [comment]
https://github.com/greenbone/gvmd/pull/741 might help here. According to @timopollmeier there might be a few additional issues which needs to be sorted out.

**Comment by tuxmaster5000** [comment]
Install gnupg2-smime will allow to install the x509 certificate.
But the mail encryption will fails with:
 d manage:WARNING:2019-09-09 07h26.15 CEST:11060: email_encrypt_smime: encryption failed
md manage:WARNING:2019-09-09 07h26.15 CEST:11060: email: S/MIME encryption failed

**Comment by tuxmaster5000** [comment]
In debug mode of gvmd I can see this:

> util gpgme:WARNING:2019-09-09 07h30.26 CEST:5829: find_email_encryption_key: No suitable key found for foo@foo.foo
> util gpgme:WARNING:2019-09-09 07h30.26 CEST:5829: encrypt_stream_internal: Could not find certificate for encryption
> md manage:WARNING:2019-09-09 07h30.26 CEST:5829: email_encrypt_smime: encryption failed
> md manage:WARNING:2019-09-09 07h30.26 CEST:5829: email: S/MIME encryption failed

**Comment by cfi-gb** [comment]
https://github.com/greenbone/gvm-libs/pull/310 / https://github.com/greenbone/gvm-libs/pull/309 seems to do additional updates to the S/MIME functionality.

**Comment by tuxmaster5000** [comment]
Today I tried again, with the patched gvm-lib (11.0) above  and gvmd (9.0), but the error is the same.

**Comment by tuxmaster5000** [comment]
Now I have used  gvm-lib (11.0.1) above and gvmd (9.0.1) but the same result.

> util gpgme:WARNING:2020-05-15 08h31.50 CEST:25464: find_email_encryption_key: No suitable key found for foo@foo.foo
> util gpgme:WARNING:2020-05-15 08h31.50 CEST:25464: encrypt_stream_internal: Could not find certificate for encryption
> md manage:WARNING:2020-05-15 08h31.50 CEST:25464: email_encrypt_smime: encryption failed
> md manage:WARNING:2020-05-15 08h31.50 CEST:25464: email: S/MIME encryption failed

**Comment by tuxmaster5000** [comment]
I will open an new one, because the import self is working.
