### ISSUE TITLE
Cmake error: No package 'sqlite3' found

### ISSUE THREAD

**Issue by testtestu** [greenbone/gvmd#564]
Hi
I try to execute 'cmake .' but it occur following error:
root@kali:~/openvas/gvmd# cmake .
-- Configuring Greenbone Vulnerability Manager...
-- Install prefix: /usr/local
-- Checking for module 'sqlite3>=3.8.3'
--   No package 'sqlite3' found
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  src/CMakeLists.txt:40 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/root/openvas/gvmd/CMakeFiles/CMakeOutput.log".
See also "/root/openvas/gvmd/CMakeFiles/CMakeError.log".

However, I already installed sqlite3_3.27.2-2

System version: Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by SStalker** [comment]
libsqlite3-dev too?

**Comment by cfi-gb** [comment]
Closing as "invalid" as only the sqlite3 development dependencies are missing and you have cross-posted this in https://community.greenbone.net/t/cmake-error-no-package-sqlite3-found/2524 as well.
