### ISSUE TITLE
Wrong NVT category in database

### ISSUE THREAD

**Issue by al3xdelarge** [greenbone/gvmd#62]
`openvasmd --rebuild` does not correctly store the category of NVTs.
Steps to verify:
```
openvasmd --rebuild`
sqlite3 /var/lib/openvas/mgr/tasks.db
sqlite> select count(*) from nvts;
52764
sqlite> select count(*) from nvts where category=11;
52764
```
This means, all NVTs are stored with category "ACT_UNKOWN" (11).
This also has impact on queries via "omp", e.g.:

```
omp '<get_nvts nvt_oid="1.3.6.1.4.1.25623.1.0.11187" details="1"/>'
<get_nvts_response status_text="OK" status="200">
_<snip>_
<category>unknown</category>
_<snip>_
```

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
