### ISSUE TITLE
PQexec failed: ERROR: syntax error at or near "report"

### ISSUE THREAD

**Issue by mettatu** [greenbone/gvmd#657]
### Expected behavior
Scan ends up with "Done" when using Postgresql as backend with 8.0.1 and a remote scanner.

### Current behavior
On master Scan gets stuck at a certain % and the gvmd logs receive "ERROR: syntax error at or near "report"". On the slave scanner the scan is finished.

### Steps to reproduce
1. Scan a target
2. See that the remote scanner has finished the scan
3. Check the logs on gvmd

### GVM versions
gsa: Greenbone Security Assistant 8.0.1
gvm: Greenbone Vulnerability Manager 8.0.1
openvas-scanner: OpenVAS Scanner 6.0.1
gvm-libs: gvm-libs-10.0.1

### Environment
**Operating system:** Debian 9

**Installation method / source:** source installation

### Logfiles

```
md manage:WARNING:2019-08-01 14h35.59 UTC:39143: sql_exec_internal: PQexec failed: ERROR:  syntax error at or near "report"
LINE 1: ...e,  description, uuid, qod, qod_type, result_nvt  report) VA...
```

**Comment by mettatu** [comment]
Fixed with:

''
diff --git a/src/manage_sql.c b/src/manage_sql.c
index cd10d9ba..58bda6ca 100644
--- a/src/manage_sql.c
+++ b/src/manage_sql.c
@@ -48519,7 +48519,7 @@ buffer_insert (GString *buffer, task_t task, const char* host,
                      "INSERT into results"
                      " (owner, date, task, host, hostname, port,"
                      "  nvt, nvt_version, severity, type,"
-                     "  description, uuid, qod, qod_type, result_nvt"
+                     "  description, uuid, qod, qod_type, result_nvt,"
                      "  report)"
                      " VALUES");
   g_string_append_printf (buffer,
''

**Comment by timopollmeier** [comment]
#658 for GVMd 8.0 and #659 for GVMd master should fix the syntax error reported here.

**Comment by mettatu** [comment]
There is still an error, I unfortunately cannot pinpoint where. gvmd.log after the patch:

```
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: sql_exec_internal: SQL: INSERT into results (owner, date, task, host, hostname, port,  nvt, nvt_version, severity, type,  description, uuid, qod, qod_type, result_nvt,  report) VALUES (2, m_now (), 187, '192.168.5.91', 'scanner-02.testing.local', '22/tcp',  '1.3.6.1.4.1.25623.1.0.10330', 'SELECT iso_time (modification_time) FROM nvts WHERE uuid = '1.3.6.1.4.1.25623.1.0.10330';', '0.0', 'Log Message',  'An ssh server is running on this port', make_uuid (), 80, 'remote_banner',  (SELECT id FROM result_nvts WHERE nvt = '1.3.6.1.4.1.25623.1.0.10330'),  205), (2, m_now (), 187, '192.168.5.91', 'scanner-02.testing.local', '22/tcp',  '1.3.6.1.4.1.25623.1.0.10267', 'SELECT iso_time (modification_time) FROM nvts WHERE uuid = '1.3.6.1.4.1.25623.1.0.10267';', '0.0', 'Log Message',  'Remote SSH server banner: SSH-2.0-OpenSSH_7.4
Remote SSH supported authentication: password,publickey
Remote SSH text/login banner: 

BANNER REMOVED

This is probably:

- OpenSSH

Concluded from remote connection attempt with credentials:

Login:    OpenVAS-VT
Password: OpenVAS-VT', make_uuid (), 80, 'remote_banner',  (SELECT id FROM result_nvts WHERE nvt = '1.3.6.1.4.1.25623.1.0.10267'),  205) RETURNING id;
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: next: sql_exec_internal failed
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: manage_cleanup_process_error: Error exit, setting running task to Interrupted
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: sql_exec_internal: PQexec failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block
 (7)
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: sql_exec_internal: SQL: UPDATE reports SET scan_run_status = 13 WHERE id = 205;
md manage:WARNING:2019-08-05 08h10.54 UTC:21335: sqlv: sql_exec_internal failed
```

**Comment by cfi-gb** [comment]
#665 and #666 seems to now contain an additional fix for this issue.

**Comment by mettatu** [comment]
Thank you, I confirm that these fixed my issue.
