### ISSUE TITLE
sql_prepare_internal: sqlite3_prepare failed: no such table: cert.sqlite_master

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/gvmd#661]
### Expected behavior

No WARNING in logs when starting gvmd

### Current behavior

WARNING in logs when starting gvmd

### Steps to reproduce
1. Use GVM-10 with components in the versions below
2. Don't have an existing cert.db and scap.db 
3. Start gvmd for the first time
4. Check gvmd.log file to see the entries below.

### GVM versions
**gvm:** 8.0.1 with SQLite3 backend
**gvm-libs:** 10.0.1

### Environment

**Installation method / source:** source installation

### Logfiles
```
md manage:   INFO:2019-08-04 09h54.08 utc:5397: sync_scap: Updating SCAP info succeeded
md manage:WARNING:2019-08-04 09h54.10 utc:5397: sql_prepare_internal: sqlite3_prepare failed: no such table: cert.sqlite_master
md manage:WARNING:2019-08-04 09h54.10 utc:5397: sqlv: sql_prepare_internal failed
```

**Comment by iotaka** [comment]
I have the same problem, so I switched to the PostgreSQL backend. I used the .deb from

https://launchpad.net/~mrazavi/+archive/ubuntu/gvm

**Comment by 7ym0n** [comment]
check sql have %, not %%.
like [issues](https://github.com/greenbone/gvmd/issues/473)

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
