### ISSUE TITLE
There are problems with the installation documentation

### ISSUE THREAD

**Issue by lixiang957** [greenbone/gvmd#693]
There are problems with the installation documentation
manage install has been with some problems

**Comment by bjoernricks** [comment]
Hi,

please explain in detail what's missing and which parts should be improved. Even better create a Pull Request to improve the documentation. Without any further information we can't help you.

**Comment by lixiang957** [comment]
have solved this problem to get this result

**Comment by lixiang957** [comment]
You can provide an official docker image for developers to use and there are still some problems with the installation process and the openvas scanner is very CPU intensive

**Comment by lixiang957** [comment]
I am doing a secondary development based on this project, using pg performance is slightly better, before using sqlite will appear internal sql error. Can you add a ip when you can have a binding domain name configuration function, usually resolve the domain name corresponding ip Scan for features similar to nessus

**Comment by lixiang957** [comment]
It would be great if you could provide an official docker image but thank you openvas is pretty good
