### ISSUE TITLE
Delete user issue

### ISSUE THREAD

**Issue by falegk** [greenbone/gvmd#71]
Hi guys,

When I try to delete a user whose tasks have been run by another user then there is a problem.
As shown below, report_counts belong to another "user" so they are not deleted, and then when it is trying to delete the reports raises a "violates foreign key constraint" problem.

This is likely to happen with other tables like host_identifiers

openvasmd-pg --version
OpenVAS Manager 7.0.3
Manager DB revision 184

```
md manage:WARNING:2018-04-13 00h33.18 EEST:27339: sql_exec_internal: SQL: DELETE FROM reports WHERE owner = 57;
md manage:WARNING:2018-04-13 00h33.18 EEST:27339: sqlv: sql_exec_internal failed
md manage:WARNING:2018-04-13 14h45.24 EEST:29936: sql_exec_internal: PQexec failed: 
ERROR:  update or delete on table "reports" violates foreign key constraint "report_counts_report_fkey" on table "report_counts"
DETAIL:  Key (id)=(3587) is still referenced from table "report_counts".
 (7)
```

Edit: Of course if I use an inheritor, works correctly.

**Comment by mattmundell** [comment]
Fixed by https://github.com/greenbone/gvmd/pull/293.

host_identifiers shouldn't be a problem because they're always owned by the owner of the report.

**Comment by falegk** [comment]
This seems to work.

Also, I would suggest that this fix must be merged to the GVM 7 version

**Comment by mattmundell** [comment]
Thanks for checking.
