### ISSUE TITLE
[7.0.3] Unable to export user credentials for remote login as an rpm package.

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvmd#74]
When I try to create the rpm package under the gsa for remote log in I only get an rpm package with 0 bytes.
Let the openvas manger run in debug mode, then an error will shown, that the create process of the rpm package will fails with:

> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_recreate: rpm_path: /tmp/rpm_4oI5X3/p.rpm
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: create temporary directory
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: temporary directory: /tmp/lsc_user_rpm_create_7c63Ku
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: copy key to temporary directory
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: Attempting RPM build
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: Spawning in /usr/share/openvas: ./openvas-lsc-rpm-creator.sh --target /tmp/lsc_user_rpm_create_7c63Ku /tmp/lsc_user_rpm_create_7c63Ku/openvas_scanner.pub
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: failed to create the rpm: 256 (WIF 1, WEX 1)
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: stdout: Verifying archive integrity... All good.
> Uncompressing OpenVAS LSC RPM creator.........................................
> LC_ALL=C ls | egrep -v "\.spec" | diff  MANIFEST - | grep "^>" | sed 's/^..//' | xargs rm -rf
> echo Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in
> Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in
> mkdir openvas-lsc-target-openvas_scanner-0.5
> cp -ar Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in openvas-lsc-target-openvas_scanner-0.5/
> tar cfzv openvas-lsc-target-openvas_scanner-0.5.tar.gz openvas-lsc-target-openvas_scanner-0.5
> openvas-lsc-target-openvas_scanner-0.5/
> openvas-lsc-target-openvas_scanner-0.5/openvas-lsc-target.spec.in
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/makeself.sh.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/makeself.lsm.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/TODO.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/makeself-header.sh.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/makeself.1.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/COPYING.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/text-base/README.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/prop-base/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/prop-base/makeself.sh.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/prop-base/makeself-header.sh.svn-base
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/props/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/tmp/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/tmp/text-base/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/tmp/prop-base/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/tmp/props/
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/entries
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/.svn/format
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/makeself.sh
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/makeself.lsm
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/TODO
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/makeself-header.sh
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/makeself.1
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/COPYING
> openvas-lsc-target-openvas_scanner-0.5/makeself-2.1.5/README
> openvas-lsc-target-openvas_scanner-0.5/lsc-pubkey.pub
> openvas-lsc-target-openvas_scanner-0.5/create-rpm.sh
> openvas-lsc-target-openvas_scanner-0.5/configure
> openvas-lsc-target-openvas_scanner-0.5/VERSION
> openvas-lsc-target-openvas_scanner-0.5/TODO
> openvas-lsc-target-openvas_scanner-0.5/RPMBASENAME
> openvas-lsc-target-openvas_scanner-0.5/README
> openvas-lsc-target-openvas_scanner-0.5/PUBKEYNAME
> openvas-lsc-target-openvas_scanner-0.5/NAME
> openvas-lsc-target-openvas_scanner-0.5/Makefile
> openvas-lsc-target-openvas_scanner-0.5/MANIFEST
> openvas-lsc-target-openvas_scanner-0.5/Changelog
> rm -rf openvas-lsc-target-openvas_scanner-0.5
> mkdir SOURCES
> mkdir RPMS
> mkdir BUILD
> mv openvas-lsc-target-openvas_scanner-0.5.tar.gz SOURCES/
> Building target platforms: noarch
> Building for target noarch
> md manage:  DEBUG:2018-04-16 07h01.26 UTC:36973: lsc_user_rpm_create: stderr: Creating directory /tmp/lsc_user_rpm_create_7c63Ku
> error: line 41: second %install
> cp: cannot stat ‘RPMS/noarch/*.rpm’: No such file or directory

Call the package creation script via hand will also fail:
mkdir /tmp/X
touch /tmp/X/sample-key.pub
/usr/share/openvas/openvas-lsc-rpm-creator.sh --target /tmp/X /tmp/X/sample-key.pub

> Creating directory /tmp/X
> Verifying archive integrity... All good.
> Uncompressing OpenVAS LSC RPM creator.........................................
> LC_ALL=C ls | egrep -v "\.spec" | diff  MANIFEST - | grep "^>" | sed 's/^..//' | xargs rm -rf
> echo Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in
> Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in
> mkdir openvas-lsc-target-sample-key-0.5
> cp -ar Changelog MANIFEST Makefile NAME PUBKEYNAME README RPMBASENAME TODO VERSION configure create-rpm.sh lsc-pubkey.pub makeself-2.1.5 openvas-lsc-target.spec.in openvas-lsc-target-sample-key-0.5/
> tar cfzv openvas-lsc-target-sample-key-0.5.tar.gz openvas-lsc-target-sample-key-0.5
> openvas-lsc-target-sample-key-0.5/
> openvas-lsc-target-sample-key-0.5/openvas-lsc-target.spec.in
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/makeself.sh.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/makeself.lsm.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/TODO.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/makeself-header.sh.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/makeself.1.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/COPYING.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/text-base/README.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/prop-base/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/prop-base/makeself.sh.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/prop-base/makeself-header.sh.svn-base
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/props/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/tmp/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/tmp/text-base/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/tmp/prop-base/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/tmp/props/
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/entries
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/.svn/format
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/makeself.sh
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/makeself.lsm
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/TODO
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/makeself-header.sh
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/makeself.1
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/COPYING
> openvas-lsc-target-sample-key-0.5/makeself-2.1.5/README
> openvas-lsc-target-sample-key-0.5/lsc-pubkey.pub
> openvas-lsc-target-sample-key-0.5/create-rpm.sh
> openvas-lsc-target-sample-key-0.5/configure
> openvas-lsc-target-sample-key-0.5/VERSION
> openvas-lsc-target-sample-key-0.5/TODO
> openvas-lsc-target-sample-key-0.5/RPMBASENAME
> openvas-lsc-target-sample-key-0.5/README
> openvas-lsc-target-sample-key-0.5/PUBKEYNAME
> openvas-lsc-target-sample-key-0.5/NAME
> openvas-lsc-target-sample-key-0.5/Makefile
> openvas-lsc-target-sample-key-0.5/MANIFEST
> openvas-lsc-target-sample-key-0.5/Changelog
> rm -rf openvas-lsc-target-sample-key-0.5
> mkdir SOURCES
> mkdir RPMS
> mkdir BUILD
> mv openvas-lsc-target-sample-key-0.5.tar.gz SOURCES/
> Building target platforms: noarch
> Building for target noarch
> error: line 41: second %install
> cp: cannot stat ‘RPMS/noarch/*.rpm’: No such file or directory

The  problem is the rpm macro in the commend block:
less /tmp/X/openvas-lsc-target.spec:
line 41:

> # %install section... do it now, and then disable it,

This line must be:

> # %%install section... do it now, and then disable it,

Because the script contains binary data and the source of it is missing in the git repo I can't create an patch for it.

**Comment by cfi-gb** [comment]
Similar to https://wald.intevation.org/tracker/index.php?func=detail&aid=6937&group_id=29&atid=220

**Comment by tuxmaster** [comment]
I have found the magic how to extract the file.
So an pull request will follow.

**Comment by bjoernricks** [comment]
Should be fixed already.
