### ISSUE TITLE
command line settings persistence

### ISSUE THREAD

**Issue by kweik** [greenbone/gvmd#740]
not an issue just a question.
Is there a way to change settings by api or conf file?

"gvmd --modify-setting 76374a7a-0569-11e6-b6da-28d24461215b \
    --value 100"

Will this setting persists through restart or reboot of the host?

**Comment by cfi-gb** [comment]
Please note the following shown when creating a new issue:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.
