### ISSUE TITLE
[7.0.3] openvas-lsc-rpm-creator.sh should not use md5 as hash algorithm.

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvmd#76]
call openvas-lsc-rpm-creator.sh --check
will result in:

> Verifying archive integrity... MD5 checksums are OK. All good.

For security reasons md5 must replaced by sha-2. Like sha-512

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
