### ISSUE TITLE
GVM 10 - REPORT NOT GENERATED

### ISSUE THREAD

**Issue by anonymous0871** [greenbone/gvmd#776]
I have installed LaTex complete packages on Ubuntu 18.04, but report is not generated.

ii  texlive                                    2017.20180305-1                         all          TeX Live: A decent selection of the TeX Live packages
ii  texlive-base                               2017.20180305-1                         all          TeX Live: Essential programs and files
ii  texlive-bibtex-extra                       2017.20180305-2                         all          TeX Live: BibTeX additional styles
ii  texlive-binaries                           2017.20170613.44572-8ubuntu0.1          amd64        Binaries for TeX Live
ii  texlive-extra-utils                        2017.20180305-2                         all          TeX Live: TeX auxiliary programs
ii  texlive-font-utils                         2017.20180305-2                         all          TeX Live: Graphics and font utilities
ii  texlive-fonts-extra                        2017.20180305-2                         all          TeX Live: Additional fonts
ii  texlive-fonts-extra-doc                    2017.20180305-2                         all          TeX Live: Documentation files for texlive-fonts-extra
ii  texlive-fonts-extra-links                  2017.20180305-2                         all          TeX Live:
ii  texlive-fonts-recommended                  2017.20180305-1                         all          TeX Live: Recommended fonts
ii  texlive-fonts-recommended-doc              2017.20180305-1                         all          TeX Live: Documentation files for texlive-fonts-recommended
ii  texlive-formats-extra                      2017.20180305-2                         all          TeX Live: Additional formats
ii  texlive-full                               2017.20180305-1                         all          TeX Live: metapackage pulling in all components of TeX Live
ii  texlive-games                              2017.20180305-2                         all          TeX Live: Games typesetting
ii  texlive-generic-extra                      2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-generic-recommended                2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-htmlxml                            2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-humanities                         2017.20180305-2                         all          TeX Live: Humanities packages
ii  texlive-humanities-doc                     2017.20180305-2                         all          TeX Live: Documentation files for texlive-humanities
ii  texlive-lang-african                       2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-lang-all                           2017.20180305-1                         all          TeX Live: metapackage depending on all TeX Live language packages
ii  texlive-lang-arabic                        2017.20180305-1                         all          TeX Live: Arabic
ii  texlive-lang-chinese                       2017.20180305-1                         all          TeX Live: Chinese
ii  texlive-lang-cjk                           2017.20180305-1                         all          TeX Live: Chinese/Japanese/Korean (base)
ii  texlive-lang-cyrillic                      2017.20180305-1                         all          TeX Live: Cyrillic
ii  texlive-lang-czechslovak                   2017.20180305-1                         all          TeX Live: Czech/Slovak
ii  texlive-lang-english                       2017.20180305-1                         all          TeX Live: US and UK English
ii  texlive-lang-european                      2017.20180305-1                         all          TeX Live: Other European languages
ii  texlive-lang-french                        2017.20180305-1                         all          TeX Live: French
ii  texlive-lang-german                        2017.20180305-1                         all          TeX Live: German
ii  texlive-lang-greek                         2017.20180305-1                         all          TeX Live: Greek
ii  texlive-lang-indic                         2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-lang-italian                       2017.20180305-1                         all          TeX Live: Italian
ii  texlive-lang-japanese                      2017.20180305-1                         all          TeX Live: Japanese
ii  texlive-lang-korean                        2017.20180305-1                         all          TeX Live: Korean
ii  texlive-lang-other                         2017.20180305-1                         all          TeX Live: Other languages
ii  texlive-lang-polish                        2017.20180305-1                         all          TeX Live: Polish
ii  texlive-lang-portuguese                    2017.20180305-1                         all          TeX Live: Portuguese
ii  texlive-lang-spanish                       2017.20180305-1                         all          TeX Live: Spanish
ii  texlive-latex-base                         2017.20180305-1                         all          TeX Live: LaTeX fundamental packages
ii  texlive-latex-base-doc                     2017.20180305-1                         all          TeX Live: Documentation files for texlive-latex-base
ii  texlive-latex-extra                        2017.20180305-2                         all          TeX Live: LaTeX additional packages
ii  texlive-latex-extra-doc                    2017.20180305-2                         all          TeX Live: Documentation files for texlive-latex-extra
ii  texlive-latex-recommended                  2017.20180305-1                         all          TeX Live: LaTeX recommended packages
ii  texlive-latex-recommended-doc              2017.20180305-1                         all          TeX Live: Documentation files for texlive-latex-recommended
ii  texlive-luatex                             2017.20180305-1                         all          TeX Live: LuaTeX packages
ii  texlive-metapost                           2017.20180305-1                         all          TeX Live: MetaPost and Metafont packages
ii  texlive-metapost-doc                       2017.20180305-1                         all          TeX Live: Documentation files for texlive-metapost
ii  texlive-music                              2017.20180305-2                         all          TeX Live: Music packages
ii  texlive-omega                              2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-pictures                           2017.20180305-1                         all          TeX Live: Graphics, pictures, diagrams
ii  texlive-pictures-doc                       2017.20180305-1                         all          TeX Live: Documentation files for texlive-pictures
ii  texlive-plain-extra                        2017.20180305-1                         all          TeX Live: transitional dummy package
ii  texlive-plain-generic                      2017.20180305-2                         all          TeX Live: Plain (La)TeX packages
ii  texlive-pstricks                           2017.20180305-2                         all          TeX Live: PSTricks
ii  texlive-pstricks-doc                       2017.20180305-2                         all          TeX Live: Documentation files for texlive-pstricks
ii  texlive-publishers                         2017.20180305-2                         all          TeX Live: Publisher styles, theses, etc.
ii  texlive-publishers-doc                     2017.20180305-2                         all          TeX Live: Documentation files for texlive-publishers
ii  texlive-science                            2017.20180305-2                         all          TeX Live: Mathematics, natural sciences, computer science packages
ii  texlive-science-doc                        2017.20180305-2                         all          TeX Live: Documentation files for texlive-science
ii  texlive-xetex                              2017.20180305-1                         all          TeX Live: XeTeX and packages

Report is empty.
No PDF, no xml, etc. no one format.
I use gvm-cli to generate tasks from bash script.

Can you help me?

Thanks
Flo

**Comment by cfi-gb** [comment]
Might be related to https://github.com/greenbone/gsa/issues/1645

**Comment by cfi-gb** [comment]
From https://github.com/greenbone/gsa/issues/1645#issuecomment-539491849:

> Solved! Iinstalled xsltproc on my Ubuntu.
> Now works like a charme.

**Comment by anonymous0871** [comment]
please read the following:
https://blog.rootshell.be/2014/11/10/ninjas-openvas-reporting/
it is an old post but solved for me
