### ISSUE TITLE
[7.0.3] export an ssh key pair as debian package will fails

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvmd#79]
After I fix the rpm part, now I found the problem the  debian package export also fails.
An 0 byte file will be generated.
/var/log/openvas/openvasmd.log:

> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_recreate: rpm_path: /tmp/rpm_7lViVe/p.rpm
> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_create: create temporary directory
> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_create: temporary directory: /tmp/lsc_user_rpm_create_oDV68U
> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_create: copy key to temporary directory
> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_create: Attempting RPM build
> md manage:  DEBUG:2018-04-16 08h20.07 UTC:555: lsc_user_rpm_create: Spawning in /usr/share/openvas: ./openvas-lsc-rpm-creator.sh --target /tmp/lsc_user_rpm_create_oDV68U /tmp/lsc_user_rpm_create_oDV68U/openvas_s
> canner.pub
> md manage:  DEBUG:2018-04-16 08h20.08 UTC:555: lsc_user_rpm_create: new filename (rpm_path): /tmp/lsc_user_rpm_create_oDV68U/openvas-lsc-target-openvas_scanner-0.5-1.noarch.rpm
> md manage:  DEBUG:2018-04-16 08h20.08 UTC:555: --- executing alien.
> md manage:  DEBUG:2018-04-16 08h20.08 UTC:555: execute_alien: Spawning in /tmp/rpm_dOxwOC/: fakeroot -- alien --scripts --keep-version p.rpm

If I read the log right, then the rpm package will called /tmp/lsc_user_rpm_create_oDV68U/openvas-lsc-target-openvas_scanner-0.5-1.noarch.rpm , but alien is called with p.rpm

Running on the command line:
`fakeroot -- alien --scripts --keep-version foo.rpm`
will .deb package will created.
foo.rpm is the created downloaded rpm package from gsa.

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
