### ISSUE TITLE
[9.0.0] compiler errror src/manage_sql_tls_certificates.c

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#791]
The build fails with:
/builddir/build/BUILD/gvmd-9.0.0/src/manage_sql_tls_certificates.c: In function 'make_tls_certificate':
/builddir/build/BUILD/gvmd-9.0.0/src/manage_sql_tls_certificates.c:654:22: error: 'new_tls_certificate' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     *tls_certificate = new_tls_certificate;

**Comment by timopollmeier** [comment]
This should be fixed with the PR above but I haven't reproduced the error, so I couldn't verify the fix myself.

**Comment by tuxmaster5000** [comment]
Yes, it will fix it.
Thanks
