### ISSUE TITLE
[9.0.0] Test don't run

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#794]
The test section of the build fails with:
ctest3 -V -j8

> UpdateCTestConfiguration  from :/builddir/build/BUILD/gvmd-9.0.0/DartConfiguration.tcl
> UpdateCTestConfiguration  from :/builddir/build/BUILD/gvmd-9.0.0/DartConfiguration.tcl
> Test project /builddir/build/BUILD/gvmd-9.0.0
> Constructing a list of tests
> Done constructing a list of tests
> Updating test list for fixtures
> Added 0 tests to meet fixture requirements
> Checking test dependency graph...
> Checking test dependency graph end
> test 1
>     Start 1: manage-utils-test
> Could not find executable manage-utils-test
> Looked in the following places:
> manage-utils-test
> manage-utils-test
> Release/manage-utils-test
> Release/manage-utils-test
> Debug/manage-utils-test
> Debug/manage-utils-test
> MinSizeRel/manage-utils-test
> MinSizeRel/manage-utils-test
> RelWithDebInfo/manage-utils-test
> RelWithDebInfo/manage-utils-test
> Deployment/manage-utils-test
> Deployment/manage-utils-test
> Development/manage-utils-test
> Development/manage-utils-test
> 
> 1: Test command: 
> 1/3 Test #1: manage-utils-test ................***Not Run   0.00 sec
> Unable to find executable: manage-utils-test
> Unable to find executable: manage-test
> Unable to find executable: gmp-tickets-test
> Errors while running CTest
> test 2
>     Start 2: manage-test
> Could not find executable manage-test
> Looked in the following places:
> manage-test
> manage-test
> Release/manage-test
> Release/manage-test
> Debug/manage-test
> Debug/manage-test
> MinSizeRel/manage-test
> MinSizeRel/manage-test
> RelWithDebInfo/manage-test
> RelWithDebInfo/manage-test
> Deployment/manage-test
> Deployment/manage-test
> Development/manage-test
> Development/manage-test
> 
> 2: Test command: 
> 2/3 Test #2: manage-test ......................***Not Run   0.00 sec
> test 3
>     Start 3: gmp-tickets-test
> Could not find executable gmp-tickets-test
> Looked in the following places:
> gmp-tickets-test
> gmp-tickets-test
> Release/gmp-tickets-test
> Release/gmp-tickets-test
> Debug/gmp-tickets-test
> Debug/gmp-tickets-test
> MinSizeRel/gmp-tickets-test
> MinSizeRel/gmp-tickets-test
> RelWithDebInfo/gmp-tickets-test
> RelWithDebInfo/gmp-tickets-test
> Deployment/gmp-tickets-test
> Deployment/gmp-tickets-test
> Development/gmp-tickets-test
> Development/gmp-tickets-test
> 
> 3: Test command: 
> 3/3 Test #3: gmp-tickets-test .................***Not Run   0.00 sec
> 
> 0% tests passed, 3 tests failed out of 3
> 
> Total Test time (real) =   0.00 sec
> 
> The following tests FAILED:
> 	  1 - manage-utils-test (Not Run)
> 	  2 - manage-test (Not Run)
> 	  3 - gmp-tickets-test (Not Run)

**Comment by timopollmeier** [comment]
To run the tests you need to build the test executables with `make tests` first because CMake does not automatically add them as dependencies to the `test` target.

**Comment by tuxmaster5000** [comment]
Yes, this will build the test, but the build itself will fails, because of an missing lib libcgreen.

>  /builddir/build/BUILD/gvmd-9.0.0/src/gmp_tickets_tests.c:22:27: fatal error: cgreen/cgreen.h: No such file or directory
>  #include <cgreen/cgreen.h>
It looks cmake don't test the presence of cgreen. After manual install it, the test passed.
