### ISSUE TITLE
[9.0.0] tools/gvm-portnames-update.in using old openvassd name

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#803]
Instant of  openvas it will try to call openvassd.
But with openvas 7, it was renamed.

**Comment by bjoernricks** [comment]
I guess this is related to https://github.com/greenbone/gvmd/pull/802

**Comment by tuxmaster5000** [comment]
Yes it is the same.

**Comment by cfi-gb** [comment]
https://github.com/greenbone/gvmd/pull/802 was merged so closing here.
