### ISSUE TITLE
Feature Request: Make permissions more granular

### ISSUE THREAD

**Issue by Chartman123** [greenbone/gvmd#806]
### Expected behavior
It should be possible to grant permissions in a way that users can see all resources, but can only modify/delete some resources based on roles/groups.

Example:
We have a group "All users" where all users are members. I then created a "Super" permission for this group, so that all created resources (tasks/targets/...) are shared with everybody. All users also have the "Observer" role, so that they can read all the resources.

I added some users to specific roles and wanted to give these roles the modify/delete/... permissions for specific role related tasks/targets. In the GSA I expected these users to be able to have the granted permissions.

### Current behavior
The specific permissions for the tasks/targets won't take effect. Users can only read or modify all resources based on their global permissions. 

### GVM versions
**gsa:** 8.0.1

**gvm:** 8.0.1

**openvas-scanner:** 6.0.1

**gvm-libs:** 10.0.1

**openvas-smb:** 1.0.5

### Environment
**Operating system:** Debian 9

**Installation method / source:** source installation

Discussion: https://community.greenbone.net/t/managing-permissions-for-roles/3597

**Comment by mattmundell** [comment]
Thanks for the input.

We've had this kind of request before, and I realise that it would be useful.  It might be easy to add a permission like "allow this user/role/group to see all my resources of type xxx".  Adding "allow this user/role/group to see all the resources of type xxx owned by this user/role/group" might not fit so well in our current model, but probably is not out of reach.

However, our permissions are pretty complex already, and our priority at the moment is performance, so I'm currently looking for ways simplify the permission system.

So yeah, it may be possible to add but is not likely to happen any time soon.
