### ISSUE TITLE
[9.0.0] Core dump starting an scan

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvmd#851]
Some times an core dump occurs on staring an scan.
Back trace:

> {   "signal": 6
> ,   "executable": "/usr/sbin/gvmd"
> ,   "stacktrace":
>       [ {   "crash_thread": true
>         ,   "frames":
>               [ {   "address": 140676187034423
>                 ,   "build_id": "398944d32cf16a67af51067a326e6c0cc14f90ed"
>                 ,   "build_id_offset": 222007
>                 ,   "function_name": "raise"
>                 ,   "file_name": "/lib64/libc.so.6"
>                 }
>               , {   "address": 140676187040296
>                 ,   "build_id": "398944d32cf16a67af51067a326e6c0cc14f90ed"
>                 ,   "build_id_offset": 227880
>                 ,   "function_name": "abort"
>                 ,   "file_name": "/lib64/libc.so.6"
>                 }
>               , {   "address": 5137701
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 943397
>                 ,   "function_name": "gmp_xml_handle_end_element"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>               , {   "address": 140676206737143
>                 ,   "build_id": "36933a0e00cf7727e701e773f3051f91bd0ee04a"
>                 ,   "build_id_offset": 325367
>                 ,   "function_name": "emit_end_element.constprop.7"
>                 ,   "file_name": "/lib64/libglib-2.0.so.0"
>                 }
>               , {   "address": 140676206740378
>                 ,   "build_id": "36933a0e00cf7727e701e773f3051f91bd0ee04a"
>                 ,   "build_id_offset": 328602
>                 ,   "function_name": "g_markup_parse_context_parse"
>                 ,   "file_name": "/lib64/libglib-2.0.so.0"
>                 }
>               , {   "address": 5253820
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 1059516
>                 ,   "function_name": "process_gmp_client_input"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>               , {   "address": 4346852
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 152548
>                 ,   "function_name": "serve_gmp"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>               , {   "address": 4334612
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 140308
>                 ,   "function_name": "serve_client"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>              , {   "address": 4325210
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 130906
>                 ,   "function_name": "accept_and_maybe_fork"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>               , {   "address": 4344209
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 149905
>                 ,   "function_name": "gvmd"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 } ]
>         }
>       , {   "frames":
>               [ {   "address": 140676187621389
>                 ,   "build_id": "398944d32cf16a67af51067a326e6c0cc14f90ed"
>                 ,   "build_id_offset": 808973
>                 ,   "function_name": "__nanosleep"
>                 ,   "file_name": "/lib64/libc.so.6"
>                 }
>               , {   "address": 140676187621028
>                 ,   "build_id": "398944d32cf16a67af51067a326e6c0cc14f90ed"
>                 ,   "build_id_offset": 808612
>                 ,   "function_name": "sleep"
>                 ,   "file_name": "/lib64/libc.so.6"
>                 }
>               , {   "address": 4334282
>                 ,   "build_id": "17909d9156ee3cf60ad2888779b97ccb45dd3f0f"
>                 ,   "build_id_offset": 139978
>                 ,   "function_name": "watch_client_connection"
>                 ,   "file_name": "/usr/sbin/gvmd"
>                 }
>               , {   "address": 140676209679973
>                 ,   "build_id": "8b33f7f8c86f8d544c63c5541a8e42b3ddfef8b1"
>                 ,   "build_id_offset": 32357
>                 ,   "function_name": "start_thread"
>                 ,   "file_name": "/lib64/libpthread.so.0"
>                 }
>               , {   "address": 140676187854989
>                 ,   "build_id": "398944d32cf16a67af51067a326e6c0cc14f90ed"
>                 ,   "build_id_offset": 1042573
>                 ,   "function_name": "__clone"
>                 ,   "file_name": "/lib64/libc.so.6"
>                 } ]
>         } ]
> }

**Comment by cfi-gb** [comment]
> gmp_xml_handle_end_element

Might be related https://github.com/greenbone/ospd/issues/169 ?

**Comment by bjoernricks** [comment]
Should be re-tested with current version. If it is still valid please re-open.
