### ISSUE TITLE
[gvmd 8.0.0] Tasks acting very weird

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gvmd#878]
### Expected behavior
Tasks run at their scheduled time.

### Current behavior
Some tasks don't run at all.
Some tasks run multiple times while only one schedule attached.

### Steps to reproduce
I've just used the GSA to setup the schedules ext.

### GVM versions
```
# gvmd --version
Greenbone Vulnerability Manager 8.0.0
Manager DB revision 205
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# gsad --version
Greenbone Security Assistant 8.0.0
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# openvassd --version
OpenVAS Scanner 6.0.0
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
# Log
There are no indicatoins in the log file that there's some issue with not starting. Looks like the task schedule part of the database is corrupted somehow?

**Comment by cfi-gb** [comment]
```
# gvmd --version
Greenbone Vulnerability Manager 8.0.0

# gsad --version
Greenbone Security Assistant 8.0.0

# openvassd --version
OpenVAS Scanner 6.0.0
```

Those are quite outdated versions of the GVM components not matching the current "oldstable":

https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208

or "stable" releases:

https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674

As stated in the reporting template please make sure to use the more recent versions first which might have already fixed your seen issue:

> Before reporting an issue please:
>
>1. make sure that you're using the latest published GVM components for the
>   release you are using: http://openvas.org/install-source.html.
