### ISSUE TITLE
gvmd not start

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/gvmd#884]
### Expected behavior
start

### Actual behavior
not start
![image](https://user-images.githubusercontent.com/17960988/69822175-774d6d00-11e4-11ea-8689-ccba3b35a8e4.png)

### Steps to reproduce

1.
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)
$ docker exec -ti newtest_gvm-gvmd_1 gvmd --version
Greenbone Vulnerability Manager 9.0.1~git-2fab12ad-master
GIT revision 2fab12ad-master
Manager DB revision 221
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas-scanner:** (openvas --version)

**gvm-libs:**
gvm-libs-11.0 - 35922a4e9ee499f6c8562b30cfbce82ff3831ee4

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

**Comment by bjoernricks** [comment]
Your postgres server can't load the binary extension from gvmd. Please fix your installation by putting  libgvm-pg-server into a path where postgres can find it.
