### ISSUE TITLE
sql_exec_internal: PQexec failed: ERROR:  each EXCEPT query must have the same number of columns

### ISSUE THREAD

**Issue by wrenchonline** [greenbone/gvmd#907]
md    gmp:WARNING:2019-12-16 05h56.28 utc:21772: Authentication failure for 'gvm' from unix_socket
md    gmp:WARNING:2019-12-16 05h56.46 utc:21789: Authentication failure for 'root' from unix_socket
md    gmp:WARNING:2019-12-16 05h56.48 utc:21792: Authentication failure for 'root' from unix_socket
event task:MESSAGE:2019-12-16 06h00.20 UTC:22066: Status of task dsdasa (a00985c3-52cc-4995-8d5d-92df1747b9e1) has changed to Requested
event task:MESSAGE:2019-12-16 06h00.20 UTC:22066: Task dsdasa (a00985c3-52cc-4995-8d5d-92df1747b9e1) has been requested to start by root
md manage:WARNING:2019-12-16 06h00.20 UTC:22077: sql_exec_internal: PQexec failed: ERROR:  each EXCEPT query must have the same number of columns
LINE 1: ...amily = 'AIX Local Security Checks' EXCEPT SELECT nvts.id, n...
                                                             ^
 (7)
md manage:WARNING:2019-12-16 06h00.20 UTC:22077: sql_exec_internal: SQL: SELECT id, uuid, name, comment,  iso_time (creation_time),  iso_time (modification_time), creation_time AS created, modification_time AS modified, '' AS _owner, 0, oid, modification_time AS version, name, cve, tag, category, family, cvss_base, cvss_base AS severity, cvss_base AS cvss, qod, qod_type, solution_type, tag AS script_tags, solution, summary, insight, affected, impact, detection, solution_method FROM nvts WHERE family = 'AIX Local Security Checks' EXCEPT SELECT nvts.id, nvts.uuid, nvts.name, nvts.comment,  iso_time (nvts.creation_time),  iso_time (nvts.modification_time), nvts.creation_time AS created, nvts.modification_time AS modified, '' AS _owner, 0, oid, modification_time AS version, nvts.name, cve, tag, category, nvts.family, cvss_base, cvss_base AS severity, cvss_base AS cvss, qod, qod_type, solution_type, tag AS script_tags, solution, summary, insight, affected, impact, detection FROM nvt_selectors, nvts WHERE nvts.family = 'AIX Local Security Checks' AND nvt_selectors.name = '54b45713-d4f4-4435-b20d-304c175ed8c5' AND nvt_selectors.family = 'AIX Local Security Checks' AND nvt_selectors.type = 2 AND nvt_selectors.exclude = 1 AND nvts.oid = nvt_selectors.family_or_nvt ORDER BY 3 ASC;
md manage:WARNING:2019-12-16 06h00.20 UTC:22077: next: sql_exec_internal failed

**Comment by wrenchonline** [comment]
＃907 I find that I don't have this table in SQL either

**Comment by bjoernricks** [comment]
Could you please provide the gvmd version?

**Comment by wrenchonline** [comment]
gvmd version:20.04 .It and the same problem with #904

**Comment by bjoernricks** [comment]
gvmd 20.04 is the current development version and therefore may of course fail every time. You should only use it if you know what you are doing. It is often better to use the latest release branch (gvmd-9.0).

But nevertheless we are going to look at this issue. Don't expect a fix before end of January.

**Comment by mattmundell** [comment]
This was fixed in https://github.com/greenbone/gvmd/pull/906.
